-- Script para a criação da tabela SEFAZ_PAR.TA_LOGRADOURO
-- Autor: Ing. Juan León Solis
-- Data: 13/Julho/2016
-- Fonte de dados: Correios - http://www.buscacep.correios.com.br/sistemas/buscacep/buscaCep.cfm

-- Create table SEFAZ_PAR.TA_LOGRADOURO
CREATE TABLE SEFAZ_PAR.TA_LOGRADOURO
(
CODIGO_LOGRADOURO CHAR(3) CONSTRAINT NN_LOGRADOURO1 NOT NULL,
DESCRICAO_LOGRADOURO VARCHAR2(20)  CONSTRAINT NN_LOGRADOURO2 NOT NULL
);

ALTER TABLE SEFAZ_PAR.TA_LOGRADOURO ADD CONSTRAINT PK_LOGRADOURO PRIMARY KEY (CODIGO_LOGRADOURO);

-- Insert rows about SEFAZ_PAR.TA_LOGRADOURO
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('001','Aeroporto');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('002','Alameda');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('003','Área');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('004','Avenida');														
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('005','Campo');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('006','Chácara');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('007','Colônia');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('008','Condomínio');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('009','Conjunto');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('010','Distrito');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('011','Esplanada');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('012','Estação');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('013','Estrada');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('014','Favela');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('015','Fazenda');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('016','Feira');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('017','Jardim');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('018','Ladeira');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('019','Lago');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('020','Lagoa');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('021','Largo');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('022','Loteamento');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('023','Morro');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('024','Núcleo');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('025','Parque');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('026','Passarela');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('027','Pátio');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('028','Praça');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('029','Quadra');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('030','Recanto');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('031','Residencial');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('032','Rodovia');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('033','Rua');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('034','Setor');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('035','Sítio');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('036','Travessa');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('037','Trecho');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('038','Trevo');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('039','Vale');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('040','Vereda');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('041','Via');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('042','Viaduto');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('043','Viela');
INSERT INTO SEFAZ_PAR.TA_LOGRADOURO(CODIGO_LOGRADOURO, DESCRICAO_LOGRADOURO) VALUES('044','Vila');
COMMIT;
