 -- The name of the ASM instance is ASMDATA.
 -- Author: Juan León 
 -- Created Date: 1st April, 2016

-- USERS
CREATE USER SEFAZ_ARR IDENTIFIED BY SEFAZ_ARR;
CREATE USER SEFAZ_PAR IDENTIFIED BY SEFAZ_PAR;
CREATE USER SEFAZ_CCI IDENTIFIED BY SEFAZ_CCI;
CREATE USER SEFAZ_CCC IDENTIFIED BY SEFAZ_CCC;
CREATE USER SEFAZ_COB IDENTIFIED BY SEFAZ_COB;
CREATE USER SEFAZ_COM IDENTIFIED BY SEFAZ_COM;
CREATE USER SEFAZ_ECF IDENTIFIED BY SEFAZ_ECF;
CREATE USER SEFAZ_FIE IDENTIFIED BY SEFAZ_FIE;
CREATE USER SEFAZ_FTR IDENTIFIED BY SEFAZ_FTR;
CREATE USER SEFAZ_GED IDENTIFIED BY SEFAZ_GED;
CREATE USER SEFAZ_ISE IDENTIFIED BY SEFAZ_ISE;
CREATE USER SEFAZ_NFE IDENTIFIED BY SEFAZ_NFE;
CREATE USER SEFAZ_OTR IDENTIFIED BY SEFAZ_OTR;
CREATE USER SEFAZ_REE IDENTIFIED BY SEFAZ_REE;
CREATE USER SEFAZ_RES IDENTIFIED BY SEFAZ_RES;
CREATE USER SEFAZ_SEG IDENTIFIED BY SEFAZ_SEG;
CREATE USER SEFAZ_WRK IDENTIFIED BY SEFAZ_WRK;

-- GRANT TO USER
GRANT CONNECT, RESOURCE TO SEFAZ_ARR;
GRANT CONNECT, RESOURCE TO SEFAZ_PAR;
GRANT CONNECT, RESOURCE TO SEFAZ_CCI;
GRANT CONNECT, RESOURCE TO SEFAZ_CCC;
GRANT CONNECT, RESOURCE TO SEFAZ_COB;
GRANT CONNECT, RESOURCE TO SEFAZ_COM;
GRANT CONNECT, RESOURCE TO SEFAZ_ECF;
GRANT CONNECT, RESOURCE TO SEFAZ_FIE;
GRANT CONNECT, RESOURCE TO SEFAZ_FTR;
GRANT CONNECT, RESOURCE TO SEFAZ_GED;
GRANT CONNECT, RESOURCE TO SEFAZ_ISE;
GRANT CONNECT, RESOURCE TO SEFAZ_NFE;
GRANT CONNECT, RESOURCE TO SEFAZ_OTR;
GRANT CONNECT, RESOURCE TO SEFAZ_REE;
GRANT CONNECT, RESOURCE TO SEFAZ_RES;
GRANT CONNECT, RESOURCE TO SEFAZ_SEG;
GRANT CONNECT, RESOURCE TO SEFAZ_WRK;
	
