-- Script para apagar as tabelas TA_PAIS, TA_ESTADO, TA_MUNICIPIO no esquema SEFAZ_PAR
-- Autor: Eng. Juan León Solis
-- Data: 27/Abril/2016

-- Esquema SEFAZ_PAR
ALTER SESSION SET CURRENT_SCHEMA = SEFAZ_PAR;

DROP TABLE SEFAZ_PAR.TA_PAIS CASCADE CONSTRAINTS;
DROP TABLE SEFAZ_PAR.TA_ESTADO CASCADE CONSTRAINTS;
DROP TABLE SEFAZ_PAR.TA_MUNICIPIO CASCADE CONSTRAINTS;