-- Script para criar a tabela TA_FERIADOS no esquema SEFAZ_PAR
-- Autor: Breno Arthur Hoffmeister
-- Data: 21 de Setembro de 2016

CREATE TABLE SEFAZ_PAR.TA_FERIADOS
    (
      DIA_FERIADO NUMBER(2) CONSTRAINT NN_FERIADOS1 NOT NULL,
      MES_FERIADO NUMBER(2) CONSTRAINT NN_FERIADOS2 NOT NULL,
      ANO_FERIADO NUMBER(4) CONSTRAINT NN_FERIADOS3 NOT NULL,
      TIPO_FERIADO CHAR(1) CONSTRAINT NN_FERIADOS4 NOT NULL,
      TXT_OBSERVA VARCHAR2(255),
	  UNIDADE_FEDERACAO char(2),
	  CODIGO_IBGE number(7),
      USUARIO_INSERCAO VARCHAR2(30) CONSTRAINT NN_FERIADOS5 NOT NULL,
      DATA_INSERCAO TIMESTAMP (6) CONSTRAINT NN_FERIADOS6 NOT NULL,
      USUARIO_ALTERACAO VARCHAR2(30),
      DATA_ALTERACAO TIMESTAMP (6),
      REGISTRO_EXCLUIDO CHAR(1) DEFAULT 'N' CONSTRAINT NN_FERIADOS7 NOT NULL,
      USUARIO_EXCLUSAO VARCHAR2(30),
      DATA_EXCLUSAO TIMESTAMP (6),
      PRIMARY KEY (DIA_FERIADO, MES_FERIADO, ANO_FERIADO)
    );

  COMMENT ON TABLE SEFAZ_PAR.TA_FERIADOS IS 'Tabela que contem os feriados Nacionais, Estaduais, Municipais do estado de Tocantins e datas em que não há expediente da SEFAZ por quaisquer outros motivos';

  COMMENT ON COLUMN SEFAZ_PAR.TA_FERIADOS.DIA_FERIADO IS 'Dia do feriado:';

  COMMENT ON COLUMN SEFAZ_PAR.TA_FERIADOS.MES_FERIADO IS 'Mes do feriado';

  COMMENT ON COLUMN SEFAZ_PAR.TA_FERIADOS.ANO_FERIADO IS 'Ano do feriado. Se 0 é comemorado anualmente';

  COMMENT ON COLUMN SEFAZ_PAR.TA_FERIADOS.TIPO_FERIADO IS 'N-Naconal, E-Estadual, M-Municipal, O-Outros';

  COMMENT ON COLUMN SEFAZ_PAR.TA_FERIADOS.TXT_OBSERVA IS 'Observações';
  
  -- privileges from another schema
  GRANT SELECT, REFERENCES ON SEFAZ_PAR.TA_FERIADOS TO SEFAZ_ARR;
  GRANT SELECT, REFERENCES ON SEFAZ_PAR.TA_FERIADOS TO SEFAZ_SEG;
  GRANT SELECT, REFERENCES ON SEFAZ_PAR.TA_FERIADOS TO SEFAZ_CCI;
  