-- Script para criar a tabela SEFAZ_ARR.TA_DARE_ORIGEM_DEBITO 
-- Autor: Breno Arthur Hoffmeister
-- Data: 23 de Setembro de 2016

  CREATE TABLE "SEFAZ_ARR"."TA_DARE_ORIGEM_DEBITO" 
   (	"ID_ORIGEM_DEBITO" NUMBER(3,0) CONSTRAINT "ORIGEM_DEBITO1" NOT NULL ENABLE, 
	"DESCRICAO" VARCHAR2(200 BYTE) CONSTRAINT "ORIGEM_DEBITO2" NOT NULL ENABLE, 
	"SITUACAO" NUMBER(1,0) CONSTRAINT "ORIGEM_DEBITO3" NOT NULL ENABLE,
	"USUARIO_INSERCAO" VARCHAR2(30 BYTE) CONSTRAINT "ORIGEM_DEBITO4" NOT NULL ENABLE, 
	"DATA_INSERCAO" TIMESTAMP (6) CONSTRAINT "ORIGEM_DEBITO5" NOT NULL ENABLE, 
	"USUARIO_ALTERACAO" VARCHAR2(30 BYTE), 
	"DATA_ALTERACAO" TIMESTAMP (6),
	"REGISTRO_EXCLUIDO" CHAR(1 BYTE) DEFAULT 'N' CONSTRAINT "ORIGEM_DEBITO6" NOT NULL ENABLE, 
	"USUARIO_EXCLUSAO" VARCHAR2(30 BYTE), 
	"DATA_EXCLUSAO" TIMESTAMP (6), 
   CONSTRAINT "PK_ID_ORIGEM_DEBITOS" PRIMARY KEY ("ID_ORIGEM_DEBITO"), 
	 CONSTRAINT "CK_ORIGEM_DEBITO1" CHECK (REGISTRO_EXCLUIDO IN ('S', 'N')) ENABLE, 
	 CONSTRAINT "CK_ORIGEM_DEBITO4" CHECK (SITUACAO IN (1,2)) ENABLE
   );
 
   COMMENT ON COLUMN "SEFAZ_ARR"."TA_DARE_ORIGEM_DEBITO"."ID_ORIGEM_DEBITO" IS 'Código da origem do débito';
   COMMENT ON COLUMN "SEFAZ_ARR"."TA_DARE_ORIGEM_DEBITO"."DESCRICAO" IS 'Descrição da origem do débito';
   COMMENT ON COLUMN "SEFAZ_ARR"."TA_DARE_ORIGEM_DEBITO"."SITUACAO" IS '1-Ativo, 2- Cancelado';
   COMMENT ON COLUMN "SEFAZ_ARR"."TA_DARE_ORIGEM_DEBITO"."USUARIO_INSERCAO" IS 'Usuário inserção do registro';
   COMMENT ON COLUMN "SEFAZ_ARR"."TA_DARE_ORIGEM_DEBITO"."DATA_INSERCAO" IS 'Data - hora inserção do registro';
   COMMENT ON COLUMN "SEFAZ_ARR"."TA_DARE_ORIGEM_DEBITO"."USUARIO_ALTERACAO" IS 'Usuário alteração do registro';
   COMMENT ON COLUMN "SEFAZ_ARR"."TA_DARE_ORIGEM_DEBITO"."DATA_ALTERACAO" IS 'Data - hora alteração do registro';
   COMMENT ON COLUMN "SEFAZ_ARR"."TA_DARE_ORIGEM_DEBITO"."REGISTRO_EXCLUIDO" IS 'Identificador do registro excluido (S) Sim ou (N) Não';
   COMMENT ON COLUMN "SEFAZ_ARR"."TA_DARE_ORIGEM_DEBITO"."USUARIO_EXCLUSAO" IS 'Usuário que fez a exclusão';
   COMMENT ON COLUMN "SEFAZ_ARR"."TA_DARE_ORIGEM_DEBITO"."DATA_EXCLUSAO" IS 'Data - hora exclusão do registro';
   COMMENT ON TABLE "SEFAZ_ARR"."TA_DARE_ORIGEM_DEBITO"  IS 'Tabela com as origens de débito para a parametrização do DARE-e.';
 
