-- Script para criar a tabela SEFAZ_ARR.TA_DARE_ORIGEM_RECEITA 
-- Autor: Breno Arthur Hoffmeister
-- Data: 23 de Setembro de 2016

  CREATE TABLE "SEFAZ_ARR"."TA_DARE_ORIGEM_RECEITA" 
   (	"ID_ORIGEM_DEBITO" NUMBER(3,0) CONSTRAINT "ORIGEM_RECEITA1" NOT NULL ENABLE, 
	"ID_RECEITA" NUMBER(4,0) CONSTRAINT "ORIGEM_RECEITA2" NOT NULL ENABLE,
	"USUARIO_INSERCAO" VARCHAR2(30 BYTE) CONSTRAINT "ORIGEM_RECEITA3" NOT NULL ENABLE, 
	"DATA_INSERCAO" TIMESTAMP (6) CONSTRAINT "ORIGEM_RECEITA4" NOT NULL ENABLE, 
	"USUARIO_ALTERACAO" VARCHAR2(30 BYTE), 
	"DATA_ALTERACAO" TIMESTAMP (6),
	"REGISTRO_EXCLUIDO" CHAR(1 BYTE) DEFAULT 'N' CONSTRAINT "ORIGEM_RECEITA5" NOT NULL ENABLE, 
	"USUARIO_EXCLUSAO" VARCHAR2(30 BYTE), 
	"DATA_EXCLUSAO" TIMESTAMP (6), 
   CONSTRAINT "PK_ID_ORIGEM_RECEITAS" PRIMARY KEY ("ID_ORIGEM_DEBITO", "ID_RECEITA")
   );
 
   COMMENT ON COLUMN "SEFAZ_ARR"."TA_DARE_ORIGEM_RECEITA"."ID_ORIGEM_DEBITO" IS 'Código da origem do débito';
   COMMENT ON COLUMN "SEFAZ_ARR"."TA_DARE_ORIGEM_RECEITA"."ID_RECEITA" IS 'Código da Receita';
   COMMENT ON COLUMN "SEFAZ_ARR"."TA_DARE_ORIGEM_RECEITA"."USUARIO_INSERCAO" IS 'Usuário inserção do registro';
   COMMENT ON COLUMN "SEFAZ_ARR"."TA_DARE_ORIGEM_RECEITA"."DATA_INSERCAO" IS 'Data - hora inserção do registro';
   COMMENT ON COLUMN "SEFAZ_ARR"."TA_DARE_ORIGEM_RECEITA"."USUARIO_ALTERACAO" IS 'Usuário alteração do registro';
   COMMENT ON COLUMN "SEFAZ_ARR"."TA_DARE_ORIGEM_RECEITA"."DATA_ALTERACAO" IS 'Data - hora alteração do registro';
   COMMENT ON COLUMN "SEFAZ_ARR"."TA_DARE_ORIGEM_RECEITA"."REGISTRO_EXCLUIDO" IS 'Identificador do registro excluido (S) Sim ou (N) Não';
   COMMENT ON COLUMN "SEFAZ_ARR"."TA_DARE_ORIGEM_RECEITA"."USUARIO_EXCLUSAO" IS 'Usuário que fez a exclusão';
   COMMENT ON COLUMN "SEFAZ_ARR"."TA_DARE_ORIGEM_RECEITA"."DATA_EXCLUSAO" IS 'Data - hora exclusão do registro';
   COMMENT ON TABLE "SEFAZ_ARR"."TA_DARE_ORIGEM_RECEITA"  IS 'Tabela com as origens de receita para a parametrização do DARE-e.';
 
