-- Script para criar a tabela SEFAZ_ARR.TA_UNIDADE_RECEITAS 
-- Autor: Breno Arthur Hoffmeister
-- Data: 23 de Setembro de 2016

  CREATE TABLE "SEFAZ_ARR"."TA_UNIDADE_RECEITAS" 
   ("IDENTIFICACAO_UNID_ORGANIZAC" NUMBER(10,0) CONSTRAINT "UNIDADE_RECEITAS1" NOT NULL ENABLE, 
	"ID_RECEITA" NUMBER(4,0) CONSTRAINT "UNIDADE_RECEITAS2" NOT NULL ENABLE,
	"USUARIO_INSERCAO" VARCHAR2(30 BYTE) CONSTRAINT "UNIDADE_RECEITAS3" NOT NULL ENABLE, 
	"DATA_INSERCAO" TIMESTAMP (6) CONSTRAINT "UNIDADE_RECEITAS4" NOT NULL ENABLE, 
	"USUARIO_ALTERACAO" VARCHAR2(30 BYTE), 
	"DATA_ALTERACAO" TIMESTAMP (6),
	"REGISTRO_EXCLUIDO" CHAR(1 BYTE) DEFAULT 'N' CONSTRAINT "UNIDADE_RECEITAS5" NOT NULL ENABLE, 
	"USUARIO_EXCLUSAO" VARCHAR2(30 BYTE), 
	"DATA_EXCLUSAO" TIMESTAMP (6), 
   CONSTRAINT "PK_ID_UNID_RECEITAS" PRIMARY KEY ("IDENTIFICACAO_UNID_ORGANIZAC", "ID_RECEITA"),
   CONSTRAINT "FK_UNID_RECEITAS_RECEITA" FOREIGN KEY("ID_RECEITA") REFERENCES "SEFAZ_ARR"."TA_RECEITAS"("ID_RECEITA")
   );
 
   COMMENT ON COLUMN "SEFAZ_ARR"."TA_UNIDADE_RECEITAS"."IDENTIFICACAO_UNID_ORGANIZAC" IS 'Número da Delegacia ou Unidade Fazendária';
   COMMENT ON COLUMN "SEFAZ_ARR"."TA_UNIDADE_RECEITAS"."ID_RECEITA" IS 'Código da Receita';
   COMMENT ON COLUMN "SEFAZ_ARR"."TA_UNIDADE_RECEITAS"."USUARIO_INSERCAO" IS 'Usuário inserção do registro';
   COMMENT ON COLUMN "SEFAZ_ARR"."TA_UNIDADE_RECEITAS"."DATA_INSERCAO" IS 'Data - hora inserção do registro';
   COMMENT ON COLUMN "SEFAZ_ARR"."TA_UNIDADE_RECEITAS"."USUARIO_ALTERACAO" IS 'Usuário alteração do registro';
   COMMENT ON COLUMN "SEFAZ_ARR"."TA_UNIDADE_RECEITAS"."DATA_ALTERACAO" IS 'Data - hora alteração do registro';
   COMMENT ON COLUMN "SEFAZ_ARR"."TA_UNIDADE_RECEITAS"."REGISTRO_EXCLUIDO" IS 'Identificador do registro excluido (S) Sim ou (N) Não';
   COMMENT ON COLUMN "SEFAZ_ARR"."TA_UNIDADE_RECEITAS"."USUARIO_EXCLUSAO" IS 'Usuário que fez a exclusão';
   COMMENT ON COLUMN "SEFAZ_ARR"."TA_UNIDADE_RECEITAS"."DATA_EXCLUSAO" IS 'Data - hora exclusão do registro';
   COMMENT ON TABLE "SEFAZ_ARR"."TA_UNIDADE_RECEITAS"  IS 'Tabela com as unidades de receita para a parametrização do DARE-e.';
 

