-- Script para criar a tabela SEFAZ_ARR.VW_TA_CONTRIBUINTES que representa os campos da VIEW  SEFAZ_ARR.VW_CONTRIBUINTES
-- Autor: Gabriel Santos
-- Data: 27 de Outubro de 2016

  CREATE TABLE "SEFAZ_ARR"."VW_TA_CONTRIBUINTES" 
   (	"TIPO_CONTRIBUINTE" NUMBER(1,0) NOT NULL ENABLE, 
	"TIPO_PESSOA" NUMBER(1,0) NOT NULL ENABLE, 
	"ID_PESSOA" NUMBER(14,0) NOT NULL ENABLE, 
	"RAZAO_SOCIAL_NOME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"SITUACAO" NUMBER(1,0) NOT NULL ENABLE, 
	"RENAVAM" NUMBER(11,0), 
	 PRIMARY KEY ("TIPO_CONTRIBUINTE", "TIPO_PESSOA", "ID_PESSOA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
   COMMENT ON COLUMN "SEFAZ_ARR"."VW_TA_CONTRIBUINTES"."TIPO_CONTRIBUINTE" IS 'Tipo de Contribuintes
1-     ICMS  
2-     IPVA  
3-     ITCD e Não Contribuintes';
   COMMENT ON COLUMN "SEFAZ_ARR"."VW_TA_CONTRIBUINTES"."TIPO_PESSOA" IS 'Tipo de Pessoa  
1-INSCRIÇÃO  
2-CNPJ   
3-CPF';
   COMMENT ON COLUMN "SEFAZ_ARR"."VW_TA_CONTRIBUINTES"."ID_PESSOA" IS 'Valor do Tipo Pessoa informado';
   COMMENT ON COLUMN "SEFAZ_ARR"."VW_TA_CONTRIBUINTES"."RAZAO_SOCIAL_NOME" IS 'Razão Social ou Nome';
   COMMENT ON COLUMN "SEFAZ_ARR"."VW_TA_CONTRIBUINTES"."SITUACAO" IS 'Situação do Tipo de grupo : 1 - ATIVO , 2 - CANCELADO ; ';
   COMMENT ON TABLE "SEFAZ_ARR"."VW_TA_CONTRIBUINTES"  IS 'TABLE das Estruturas que envolvem os tipos de contribuintes no SAT';
 
