-- Script para criar a tabela SEFAZ_ARR.VW_TA_DEBITOS_CONTA_CORRENTE que representa os campos da VIEW  SEFAZ_ARR.VW_DEBITOS_CONTA_CORRENTE
-- Autor: Gabriel Santos
-- Data: 27 de Outubro de 2016

  CREATE TABLE "SEFAZ_ARR"."VW_TA_DEBITOS_CONTA_CORRENTE" 
   (	"ID_CONTA_CORRENTE" NUMBER(15,0) NOT NULL ENABLE, 
	"TIPO_CONTA" NUMBER(2,0) NOT NULL ENABLE, 
	"TIPO_PESSOA" NUMBER(1,0) NOT NULL ENABLE, 
	"ID_PESSOA" NUMBER(14,0) NOT NULL ENABLE, 
	"RENAVAM" NUMBER(12,0), 
	"DOCUMENTO" NUMBER(15,0) NOT NULL ENABLE, 
	"RECEITA" NUMBER(5,0) NOT NULL ENABLE, 
	"PERIODO_REFERENCIA" NUMBER(6,0) NOT NULL ENABLE, 
	"DATA_VENCIMENTO" DATE NOT NULL ENABLE, 
	"VALOR_IMPOSTO" NUMBER(14,2), 
	"VALOR_CORRECAO_MONET" NUMBER(14,2), 
	"VALOR_MULTA" NUMBER(14,2), 
	"VALOR_REDUCAO_MULTA" NUMBER(14,2), 
	"VALOR_MULTA_FISCAL" NUMBER(14,2), 
	"VALOR_REDUCAO_MULTA_FISCAL" NUMBER(14,2), 
	"VALOR_JUROS" NUMBER(14,2), 
	"VALOR_REDUCAO_JUROS" NUMBER(14,2), 
	"VALOR_TOTAL_DEVIDO" NUMBER(14,2) NOT NULL ENABLE, 
	"SITUACAO" NUMBER(1,0), 
	 PRIMARY KEY ("ID_CONTA_CORRENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "SEFAZ_ARR"."VW_TA_DEBITOS_CONTA_CORRENTE"."ID_CONTA_CORRENTE" IS 'Número sequencial da Conta Corrente';
   COMMENT ON COLUMN "SEFAZ_ARR"."VW_TA_DEBITOS_CONTA_CORRENTE"."TIPO_CONTA" IS 'Os débitos de conta corrente com Documentos associados, são os seguintes tipos:     
01 – Declarado ICMS,      
02 – Declarado ICMS ST      
03 – Declarado ICMS Complementar     
04 – Cobrança Trânsito
05 – Auto de Infração / NLD     
06 – Parcelamento
07 – Parcelamento Divida Ativa  
08 – Divida Ativa     
14 - ITCD
12 – DPCA';
   COMMENT ON COLUMN "SEFAZ_ARR"."VW_TA_DEBITOS_CONTA_CORRENTE"."TIPO_PESSOA" IS 'Tipo de Informação que está sendo colocado no campo ID_PESSOA.
1 - INSCRICAO
2 - CNPJ
3 - CPF';
   COMMENT ON COLUMN "SEFAZ_ARR"."VW_TA_DEBITOS_CONTA_CORRENTE"."ID_PESSOA" IS 'Campo responsável para identificar o dono do débito, podendo ser uma inscrição ou cpf ou cnpj';
   COMMENT ON COLUMN "SEFAZ_ARR"."VW_TA_DEBITOS_CONTA_CORRENTE"."RENAVAM" IS 'Campo do Renavan do Carro quando o tipo do débito for de IPVA';
   COMMENT ON COLUMN "SEFAZ_ARR"."VW_TA_DEBITOS_CONTA_CORRENTE"."DOCUMENTO" IS 'Número do Documento podendo ser um Auto de Infração, número da declaração, número do itcd e demais documentos.';
   COMMENT ON COLUMN "SEFAZ_ARR"."VW_TA_DEBITOS_CONTA_CORRENTE"."RECEITA" IS 'Código de receita';
   COMMENT ON COLUMN "SEFAZ_ARR"."VW_TA_DEBITOS_CONTA_CORRENTE"."PERIODO_REFERENCIA" IS 'Periodo de Referência do débito podendo ser um Ano com 4 posiçoes ou um periodo com mês de 2 posições e um ano com 4 posições.';
   COMMENT ON COLUMN "SEFAZ_ARR"."VW_TA_DEBITOS_CONTA_CORRENTE"."DATA_VENCIMENTO" IS 'Data de Vencimento do Débito com DD/MM/YYYY.';
   COMMENT ON COLUMN "SEFAZ_ARR"."VW_TA_DEBITOS_CONTA_CORRENTE"."VALOR_IMPOSTO" IS 'Valor do Imposto';
   COMMENT ON COLUMN "SEFAZ_ARR"."VW_TA_DEBITOS_CONTA_CORRENTE"."VALOR_CORRECAO_MONET" IS 'Valor Correção Monetária';
   COMMENT ON COLUMN "SEFAZ_ARR"."VW_TA_DEBITOS_CONTA_CORRENTE"."VALOR_MULTA" IS 'Valor da Multa Acessória';
   COMMENT ON COLUMN "SEFAZ_ARR"."VW_TA_DEBITOS_CONTA_CORRENTE"."VALOR_REDUCAO_MULTA" IS 'Valor da Redução da Multa';
   COMMENT ON COLUMN "SEFAZ_ARR"."VW_TA_DEBITOS_CONTA_CORRENTE"."VALOR_MULTA_FISCAL" IS 'Valor Redução da Multa de Ação Fiscal';
   COMMENT ON COLUMN "SEFAZ_ARR"."VW_TA_DEBITOS_CONTA_CORRENTE"."VALOR_REDUCAO_MULTA_FISCAL" IS 'VAlor da Redução da Multa Fiscal';
   COMMENT ON COLUMN "SEFAZ_ARR"."VW_TA_DEBITOS_CONTA_CORRENTE"."VALOR_JUROS" IS 'Valor do Juros';
   COMMENT ON COLUMN "SEFAZ_ARR"."VW_TA_DEBITOS_CONTA_CORRENTE"."VALOR_REDUCAO_JUROS" IS 'Valor de Redução dos Juros';
   COMMENT ON COLUMN "SEFAZ_ARR"."VW_TA_DEBITOS_CONTA_CORRENTE"."VALOR_TOTAL_DEVIDO" IS 'Valor Total do Débito';
   COMMENT ON TABLE "SEFAZ_ARR"."VW_TA_DEBITOS_CONTA_CORRENTE"  IS 'TABLE com os Débitos existentes e atualizados que encontram-se com o débitos';