-- Script para criar a tabela SEFAZ_ARR.VW_TA_NOTA_AVULSA que representa os campos da VIEW  SEFAZ_ARR.VW_TA_NOTA_AVULSA
-- Autor: Gabriel Santos
-- Data: 27 de Outubro de 2016

  CREATE TABLE "SEFAZ_ARR"."VW_TA_NOTA_AVULSA" 
   (	"ID_NFA" NUMBER(15,0) NOT NULL ENABLE, 
	"ID_EMITENTE" NUMBER(14,0) NOT NULL ENABLE, 
	"ID_INSCRICAO_EMITENTE" NUMBER(9,0), 
	"DESCRICAO_EMITENTE" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"ID_DESTINATARIO" NUMBER(14,0) NOT NULL ENABLE, 
	"ID_INSCRICAO_DESTINATARIO" NUMBER(9,0), 
	"DESCRICAO_DESTINATARIO" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"VALOR_DEVIDO" NUMBER(14,2) NOT NULL ENABLE, 
	"ID_RECEITA" NUMBER(5,0) NOT NULL ENABLE, 
	"ID_RECEITA_TAXA" NUMBER(5,0), 
	"ID_RECEITA_SUBCODIGO" NUMBER(3,0), 
	"VALOR_TSE" NUMBER(14,2), 
	 PRIMARY KEY ("ID_NFA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "SEFAZ_ARR"."VW_TA_NOTA_AVULSA"."ID_NFA" IS 'Número da Nota Avulta';
   COMMENT ON COLUMN "SEFAZ_ARR"."VW_TA_NOTA_AVULSA"."ID_EMITENTE" IS 'Emitente da Nota Avulta';
   COMMENT ON COLUMN "SEFAZ_ARR"."VW_TA_NOTA_AVULSA"."ID_INSCRICAO_EMITENTE" IS 'Inscrição do Emitente';
   COMMENT ON COLUMN "SEFAZ_ARR"."VW_TA_NOTA_AVULSA"."DESCRICAO_EMITENTE" IS 'nome do emitente';
   COMMENT ON COLUMN "SEFAZ_ARR"."VW_TA_NOTA_AVULSA"."ID_DESTINATARIO" IS 'Destinatário da Nota';
   COMMENT ON COLUMN "SEFAZ_ARR"."VW_TA_NOTA_AVULSA"."ID_INSCRICAO_DESTINATARIO" IS 'Inscrição do Destinatário';
   COMMENT ON COLUMN "SEFAZ_ARR"."VW_TA_NOTA_AVULSA"."DESCRICAO_DESTINATARIO" IS 'nome do destinatário';
   COMMENT ON COLUMN "SEFAZ_ARR"."VW_TA_NOTA_AVULSA"."VALOR_DEVIDO" IS 'Valor do Débito';
   COMMENT ON COLUMN "SEFAZ_ARR"."VW_TA_NOTA_AVULSA"."ID_RECEITA" IS 'Código da Receita do Valor Devido';
   COMMENT ON COLUMN "SEFAZ_ARR"."VW_TA_NOTA_AVULSA"."ID_RECEITA_TAXA" IS 'Código da Taxa de Emissão da NFA ';
   COMMENT ON COLUMN "SEFAZ_ARR"."VW_TA_NOTA_AVULSA"."ID_RECEITA_SUBCODIGO" IS 'SubCódigo da Taxa';
   COMMENT ON COLUMN "SEFAZ_ARR"."VW_TA_NOTA_AVULSA"."VALOR_TSE" IS 'Valor Devido da Taxa ';
   COMMENT ON TABLE "SEFAZ_ARR"."VW_TA_NOTA_AVULSA"  IS 'TABLE de Notas Avulsas que foram geradas e não pagas.';
