-- Script para criar a VIEW SEFAZ_ARR.VW_DEBITOS_CONTA_CORRENTE
-- Autor: Gabriel Santos
-- Data: 27 de Outubro de 2016

  CREATE OR REPLACE FORCE VIEW "SEFAZ_ARR"."VW_DEBITOS_CONTA_CORRENTE" ("ID_CONTA_CORRENTE", "TIPO_CONTA", "TIPO_PESSOA", "ID_PESSOA", "RENAVAM", "DOCUMENTO", "RECEITA", "PERIODO_REFERENCIA", "DATA_VENCIMENTO", "VALOR_IMPOSTO", "VALOR_CORRECAO_MONET", "VALOR_MULTA", "VALOR_REDUCAO_MULTA", "VALOR_MULTA_FISCAL", "VALOR_REDUCAO_MULTA_FISCAL", "VALOR_JUROS", "VALOR_REDUCAO_JUROS", "VALOR_TOTAL_DEVIDO", "SITUACAO") AS 
  SELECT "ID_CONTA_CORRENTE","TIPO_CONTA","TIPO_PESSOA","ID_PESSOA","RENAVAM","DOCUMENTO","RECEITA","PERIODO_REFERENCIA","DATA_VENCIMENTO","VALOR_IMPOSTO","VALOR_CORRECAO_MONET","VALOR_MULTA","VALOR_REDUCAO_MULTA","VALOR_MULTA_FISCAL","VALOR_REDUCAO_MULTA_FISCAL","VALOR_JUROS","VALOR_REDUCAO_JUROS","VALOR_TOTAL_DEVIDO","SITUACAO" FROM SEFAZ_ARR.VW_TA_DEBITOS_CONTA_CORRENTE;
 
