-- Script para criar a VIEW SEFAZ_ARR.VW_NOTA_AVULSA
-- Autor: Gabriel Santos
-- Data: 27 de Outubro de 2016

CREATE OR REPLACE FORCE VIEW "SEFAZ_ARR"."VW_NOTA_AVULSA" ("ID_NFA", "ID_EMITENTE", "ID_INSCRICAO_EMITENTE", "DESCRICAO_EMITENTE", "ID_DESTINATARIO", "ID_INSCRICAO_DESTINATARIO", "DESCRICAO_DESTINATARIO", "VALOR_DEVIDO", "ID_RECEITA", "ID_RECEITA_TAXA", "ID_RECEITA_SUBCODIGO", "VALOR_TSE") AS 
SELECT "ID_NFA","ID_EMITENTE","ID_INSCRICAO_EMITENTE","DESCRICAO_EMITENTE","ID_DESTINATARIO","ID_INSCRICAO_DESTINATARIO","DESCRICAO_DESTINATARIO","VALOR_DEVIDO","ID_RECEITA","ID_RECEITA_TAXA","ID_RECEITA_SUBCODIGO","VALOR_TSE" FROM SEFAZ_ARR.VW_TA_NOTA_AVULSA;
 
