-- Script para criar a VIEW SEFAZ_ARR.VW_DEBITOS_CONTA_CORRENTE
-- Autor: Gabriel Santos
-- Data: 27 de Outubro de 2016

ALTER TABLE SEFAZ_ARR.TA_DARE MODIFY NOME_RAZAO_SOCIAL VARCHAR2(255 BYTE) NULL;