#!/bin/bash
# save the file as <git_directory>/.git/hooks/pre-commit

echo "Running Maven clean compile, test, checkstyle and pmd"

# running maven compile all
echo ""
echo "------- Starting to compile the code"
mvn clean compile test-compile
if [ $? -ne 0 ]; then

  echo ""
  echo "------- Error while compiling the code"
  exit 1
fi

# running maven clean test
echo ""
echo "------- Starting to test the code"
mvn test
if [ $? -ne 0 ]; then

  echo ""
  echo "------- Error while testing the code"
  exit 1
fi

# running maven checkstyle:check
echo ""
echo "------- Starting to check the code with Checkstyle"
mvn checkstyle:check
if [ $? -ne 0 ]; then

  echo ""
  echo "------- Error while checking the code with Checkstyle"
  exit 1
fi

# running maven pmd:check
echo ""
echo "------- Starting to check the code with PMD"
mvn pmd:check
if [ $? -ne 0 ]; then

  echo ""
  echo "------- Error while checking the code with PMD"
  exit 1
fi