-- Script para alterar a tabela TA_LOG_NAVEGACAO incluindo as colunas CPF_CNPJ_PROCURADO e URL_ACESSO
-- Autor: Volceri D'ávila
-- Data: 05 de setembro de 2016

-- privileges from another schema
GRANT SELECT, REFERENCES ON SEFAZ_CCI.TA_PESSOA_JURIDICA TO SEFAZ_SEG;
GRANT SELECT, REFERENCES ON SEFAZ_CCI.TA_REPRESENTANTE_LEGAL TO SEFAZ_SEG;

ALTER TABLE SEFAZ_SEG.TA_LOG_NAVEGACAO ADD (CPF_CNPJ_PROCURADO  VARCHAR2(14));
ALTER TABLE SEFAZ_SEG.TA_LOG_NAVEGACAO ADD (URL_ACESSO  VARCHAR2(400));
