/*	CONSULTAS DE SEGURANÇA	*/
INSERT INTO SEFAZ_SEG.TA_APLICACAO_MODULO (IDENTIFICACAO_APLICACAO_MODULO, IDENTIFICACAO_MODULO_SISTEMA, DESCRICAO_APLICACAO_MODULO, USUARIO_INSERCAO, DATA_INSERCAO) SELECT SEFAZ_SEG.SQ_APLICACAO_MODULO.NEXTVAL, IDENTIFICACAO_MODULO_SISTEMA, 'CONSULTA', user, current_timestamp FROM SEFAZ_SEG.TA_MODULO_SISTEMA WHERE ABREVIACAO_MODULO = 'SEG';

INSERT INTO SEFAZ_SEG.TA_OPCAO_APLICACAO (IDENTIFICACAO_OPCAO_APLICACAO, IDENTIFICACAO_APLICACAO_MODULO, CASO_USO, OPCAO_URL, DESCRIPCAO_OPCAO, AJUDA_OPCAO, USUARIO_INSERCAO, DATA_INSERCAO)
SELECT 
SEFAZ_SEG.SQ_OPCAO_APLICACAO.NEXTVAL, IDENTIFICACAO_APLICACAO_MODULO, 'SEGUC0630', 'seg/consulta/consulta-historico-navegacao.jsf', 'Consultar histórico de acesso (log)', 'Ajuda para consultar histórico de acesso (log)', user,current_timestamp FROM SEFAZ_SEG.TA_APLICACAO_MODULO am INNER JOIN SEFAZ_SEG.TA_MODULO_SISTEMA sm ON am.IDENTIFICACAO_MODULO_SISTEMA = sm.IDENTIFICACAO_MODULO_SISTEMA
WHERE ABREVIACAO_MODULO = 'SEG' AND DESCRICAO_APLICACAO_MODULO = 'CONSULTA';

INSERT INTO SEFAZ_SEG.TA_OPCAO_APLICACAO (IDENTIFICACAO_OPCAO_APLICACAO, IDENTIFICACAO_APLICACAO_MODULO, CASO_USO, OPCAO_URL, DESCRIPCAO_OPCAO, AJUDA_OPCAO, USUARIO_INSERCAO, DATA_INSERCAO) 
SELECT
SEFAZ_SEG.SQ_OPCAO_APLICACAO.NEXTVAL, IDENTIFICACAO_APLICACAO_MODULO, 'SCEUC0003', 'seg/consulta/consulta-comunicacao-contribuinte.jsf', 'Consulta de comunicações com os contribuintes', 'Ajuda para consulta de comunicações com os contribuintes', user, current_timestamp FROM SEFAZ_SEG.TA_APLICACAO_MODULO am INNER JOIN SEFAZ_SEG.TA_MODULO_SISTEMA sm ON am.IDENTIFICACAO_MODULO_SISTEMA = sm.IDENTIFICACAO_MODULO_SISTEMA
WHERE ABREVIACAO_MODULO = 'SEG' AND DESCRICAO_APLICACAO_MODULO = 'CONSULTA';