-- Script para inserir as aplicações e opções do sistema respectivamente em TA_APLICACAO_MODULO e TA_OPCAO_APLICACAO
-- Autor: Cristiano Luis Schwaab
-- Data: 13 de junho de 2016

--GESTÃO SEGURANÇA
INSERT INTO SEFAZ_SEG.TA_APLICACAO_MODULO (IDENTIFICACAO_APLICACAO_MODULO, IDENTIFICACAO_MODULO_SISTEMA, DESCRICAO_APLICACAO_MODULO, USUARIO_INSERCAO, DATA_INSERCAO) SELECT SEFAZ_SEG.SQ_APLICACAO_MODULO.NEXTVAL, IDENTIFICACAO_MODULO_SISTEMA, 'GESTÃO', user, current_timestamp FROM SEFAZ_SEG.TA_MODULO_SISTEMA WHERE ABREVIACAO_MODULO = 'SEG';

INSERT INTO SEFAZ_SEG.TA_OPCAO_APLICACAO (IDENTIFICACAO_OPCAO_APLICACAO, IDENTIFICACAO_APLICACAO_MODULO, CASO_USO, OPCAO_URL, DESCRIPCAO_OPCAO, AJUDA_OPCAO, USUARIO_INSERCAO, DATA_INSERCAO)
SELECT 
SEFAZ_SEG.SQ_OPCAO_APLICACAO.NEXTVAL, IDENTIFICACAO_APLICACAO_MODULO, 'SEGUC0010', 'seg/gestao/unidades-organizacionais.jsf', 'Manutenção das unidades organizacionais', 'url_wiki', user,current_timestamp FROM SEFAZ_SEG.TA_APLICACAO_MODULO am INNER JOIN SEFAZ_SEG.TA_MODULO_SISTEMA sm ON am.IDENTIFICACAO_MODULO_SISTEMA = sm.IDENTIFICACAO_MODULO_SISTEMA
WHERE ABREVIACAO_MODULO = 'SEG' AND DESCRICAO_APLICACAO_MODULO = 'GESTÃO';

INSERT INTO SEFAZ_SEG.TA_OPCAO_APLICACAO (IDENTIFICACAO_OPCAO_APLICACAO, IDENTIFICACAO_APLICACAO_MODULO, CASO_USO, OPCAO_URL, DESCRIPCAO_OPCAO, AJUDA_OPCAO, USUARIO_INSERCAO, DATA_INSERCAO) 
SELECT
SEFAZ_SEG.SQ_OPCAO_APLICACAO.NEXTVAL, IDENTIFICACAO_APLICACAO_MODULO, 'SEGUC0020', 'seg/gestao/posto-trabalho.jsf', 'Manter Postos de trabalho', 'url_wiki', user, current_timestamp FROM SEFAZ_SEG.TA_APLICACAO_MODULO am INNER JOIN SEFAZ_SEG.TA_MODULO_SISTEMA sm ON am.IDENTIFICACAO_MODULO_SISTEMA = sm.IDENTIFICACAO_MODULO_SISTEMA
WHERE ABREVIACAO_MODULO = 'SEG' AND DESCRICAO_APLICACAO_MODULO = 'GESTÃO';

INSERT INTO SEFAZ_SEG.TA_OPCAO_APLICACAO (IDENTIFICACAO_OPCAO_APLICACAO, IDENTIFICACAO_APLICACAO_MODULO, CASO_USO, OPCAO_URL, DESCRIPCAO_OPCAO, AJUDA_OPCAO, USUARIO_INSERCAO, DATA_INSERCAO) 
SELECT
SEFAZ_SEG.SQ_OPCAO_APLICACAO.NEXTVAL, IDENTIFICACAO_APLICACAO_MODULO, 'SEGUC0030', 'seg/gestao/tipo-usuario.jsf', 'Consulta do tipo de usuário', 'url_wiki', user, current_timestamp FROM SEFAZ_SEG.TA_APLICACAO_MODULO am INNER JOIN SEFAZ_SEG.TA_MODULO_SISTEMA sm ON am.IDENTIFICACAO_MODULO_SISTEMA = sm.IDENTIFICACAO_MODULO_SISTEMA
WHERE ABREVIACAO_MODULO = 'SEG' AND DESCRICAO_APLICACAO_MODULO = 'GESTÃO';

INSERT INTO SEFAZ_SEG.TA_OPCAO_APLICACAO (IDENTIFICACAO_OPCAO_APLICACAO, IDENTIFICACAO_APLICACAO_MODULO, CASO_USO, OPCAO_URL, DESCRIPCAO_OPCAO, AJUDA_OPCAO, USUARIO_INSERCAO, DATA_INSERCAO) SELECT
SEFAZ_SEG.SQ_OPCAO_APLICACAO.NEXTVAL, IDENTIFICACAO_APLICACAO_MODULO, 'SEGUC0030', 'seg/gestao/manter-tipo-usuario.jsf', 'Manutenção do tipo de usuário', 'url_wiki', user, current_timestamp FROM SEFAZ_SEG.TA_APLICACAO_MODULO am INNER JOIN SEFAZ_SEG.TA_MODULO_SISTEMA sm ON am.IDENTIFICACAO_MODULO_SISTEMA = sm.IDENTIFICACAO_MODULO_SISTEMA
WHERE ABREVIACAO_MODULO = 'SEG' AND DESCRICAO_APLICACAO_MODULO = 'GESTÃO';

INSERT INTO SEFAZ_SEG.TA_OPCAO_APLICACAO (IDENTIFICACAO_OPCAO_APLICACAO, IDENTIFICACAO_APLICACAO_MODULO, CASO_USO, OPCAO_URL, DESCRIPCAO_OPCAO, AJUDA_OPCAO, USUARIO_INSERCAO, DATA_INSERCAO) SELECT 
SEFAZ_SEG.SQ_OPCAO_APLICACAO.NEXTVAL, IDENTIFICACAO_APLICACAO_MODULO, 'SEGUC0130', 'seg/gestao/consulta-usuario-sistema.jsf', 'Consulta de usuário', 'url_wiki', user, current_timestamp FROM SEFAZ_SEG.TA_APLICACAO_MODULO am INNER JOIN SEFAZ_SEG.TA_MODULO_SISTEMA sm ON am.IDENTIFICACAO_MODULO_SISTEMA = sm.IDENTIFICACAO_MODULO_SISTEMA
WHERE ABREVIACAO_MODULO = 'SEG' AND DESCRICAO_APLICACAO_MODULO = 'GESTÃO';

INSERT INTO SEFAZ_SEG.TA_OPCAO_APLICACAO (IDENTIFICACAO_OPCAO_APLICACAO, IDENTIFICACAO_APLICACAO_MODULO, CASO_USO, OPCAO_URL, DESCRIPCAO_OPCAO, AJUDA_OPCAO, USUARIO_INSERCAO, DATA_INSERCAO) SELECT 
SEFAZ_SEG.SQ_OPCAO_APLICACAO.NEXTVAL, IDENTIFICACAO_APLICACAO_MODULO, 'SEGUC0050', 'seg/gestao/cria-usuario-senha.jsf', 'Criação do usuário/senha no sistema', 'url_wiki', user, current_timestamp FROM SEFAZ_SEG.TA_APLICACAO_MODULO am INNER JOIN SEFAZ_SEG.TA_MODULO_SISTEMA sm ON am.IDENTIFICACAO_MODULO_SISTEMA = sm.IDENTIFICACAO_MODULO_SISTEMA
WHERE ABREVIACAO_MODULO = 'SEG' AND DESCRICAO_APLICACAO_MODULO = 'GESTÃO';

INSERT INTO SEFAZ_SEG.TA_OPCAO_APLICACAO (IDENTIFICACAO_OPCAO_APLICACAO, IDENTIFICACAO_APLICACAO_MODULO, CASO_USO, OPCAO_URL, DESCRIPCAO_OPCAO, AJUDA_OPCAO, USUARIO_INSERCAO, DATA_INSERCAO) SELECT 
SEFAZ_SEG.SQ_OPCAO_APLICACAO.NEXTVAL, IDENTIFICACAO_APLICACAO_MODULO, 'SEGUC0070', 'seg/gestao/ativar-inativar-perfil.jsf', 'Ativar/Inativar perfis dos Funcionários SEFAZ', 'url_wiki', user, current_timestamp FROM SEFAZ_SEG.TA_APLICACAO_MODULO am INNER JOIN SEFAZ_SEG.TA_MODULO_SISTEMA sm ON am.IDENTIFICACAO_MODULO_SISTEMA = sm.IDENTIFICACAO_MODULO_SISTEMA
WHERE ABREVIACAO_MODULO = 'SEG' AND DESCRICAO_APLICACAO_MODULO = 'GESTÃO';

INSERT INTO SEFAZ_SEG.TA_OPCAO_APLICACAO (IDENTIFICACAO_OPCAO_APLICACAO, IDENTIFICACAO_APLICACAO_MODULO, CASO_USO, OPCAO_URL, DESCRIPCAO_OPCAO, AJUDA_OPCAO, USUARIO_INSERCAO, DATA_INSERCAO) SELECT 
SEFAZ_SEG.SQ_OPCAO_APLICACAO.NEXTVAL, IDENTIFICACAO_APLICACAO_MODULO, 'SEGUC0060', 'seg/gestao/manter-usuario-sistema.jsf', 'Manutenção de usuário', 'url_wiki', user, current_timestamp FROM SEFAZ_SEG.TA_APLICACAO_MODULO am INNER JOIN SEFAZ_SEG.TA_MODULO_SISTEMA sm ON am.IDENTIFICACAO_MODULO_SISTEMA = sm.IDENTIFICACAO_MODULO_SISTEMA
WHERE ABREVIACAO_MODULO = 'SEG' AND DESCRICAO_APLICACAO_MODULO = 'GESTÃO';