-- Script para alterar a tabela TA_UNIDADE_ORGANIZACIONAL incluindo a coluna TIPO_UNIDADE
-- Autor: Cristiano Luis Schwaab
-- Data: 13 de junho de 2016

-- Esquema SEFAZ_SEG
ALTER SESSION SET CURRENT_SCHEMA = SEFAZ_SEG;

ALTER TABLE SEFAZ_SEG.TA_UNIDADE_ORGANIZACIONAL
ADD TIPO_UNIDADE CHAR(1) DEFAULT 'U' NOT NULL;

ALTER TABLE SEFAZ_SEG.TA_UNIDADE_ORGANIZACIONAL MODIFY TIPO_UNIDADE DEFAULT NULL;