-- Script para a remover a tabela SEFAZ_SEG.TA_TIPO_USUARIO
-- Autor: Cristiano Luis Schwaab
-- Data: 27 de Setembro de 2016

ALTER TABLE SEFAZ_SEG.TA_USUARIO_SISTEMA DROP CONSTRAINT FK_USUARIO_SISTEMA1;

DROP TABLE SEFAZ_SEG.TA_TIPO_USUARIO;

COMMIT;
