-- Script para criar as tabelas no esquema SEFAZ_SEG com as PK, CK, FK e comentarios 
-- Autor: Eng. Juan León Solis
-- Data: 03/Mayo/2016

-- privileges from another schema
GRANT SELECT, REFERENCES ON SEFAZ_PAR.TA_ESTADO TO SEFAZ_SEG;
GRANT SELECT, REFERENCES ON SEFAZ_PAR.TA_MUNICIPIO TO SEFAZ_SEG;
GRANT SELECT, REFERENCES ON SEFAZ_PAR.TA_PARAMETRO_GERAL TO SEFAZ_SEG;

-- Esquema SEFAZ_SEG
ALTER SESSION SET CURRENT_SCHEMA = SEFAZ_SEG;

CREATE SEQUENCE SEFAZ_SEG.SQ_USUARIO_PRINCIPAL_EMPRESA MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEFAZ_SEG.SQ_PROCURACAO_USUARIO MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEFAZ_SEG.SQ_PROCURACAO_OPCAO MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEFAZ_SEG.SQ_SOLICITACAO_USUARIO MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEFAZ_SEG.SQ_POSTO_TRABALHO MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEFAZ_SEG.SQ_UNIDADE_ORGANIZACIONAL MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEFAZ_SEG.SQ_SMS_CONTRIBUINTE MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEFAZ_SEG.SQ_HISTORICO_LOGIN_SISTEMA MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEFAZ_SEG.SQ_PAPEL_SISTEMA MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEFAZ_SEG.SQ_OPCAO_APLICACAO MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEFAZ_SEG.SQ_APLICACAO_MODULO MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEFAZ_SEG.SQ_MODULO_SISTEMA MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEFAZ_SEG.SQ_PERFIL_SISTEMA MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEFAZ_SEG.SQ_USUARIO_PERFIL MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEFAZ_SEG.SQ_TIPO_USUARIO MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEFAZ_SEG.SQ_LOG_NAVEGACAO MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEFAZ_SEG.SQ_CORREIO_CONTRIBUINTE MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEFAZ_SEG.SQ_ERRO_PROCESSO_AUDITORIA MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEFAZ_SEG.SQ_OPERACAO_AUDITADA MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE SEFAZ_SEG.TA_USUARIO_POSTO_TRABALHO (
  IDENTIFICACAO_POSTO_TRABALHO number(10) CONSTRAINT NN_USUARIO_POSTO_TRABALHO1 NOT NULL, 
  CPF_USUARIO                  varchar2(11) CONSTRAINT NN_USUARIO_POSTO_TRABALHO2 NOT NULL,
  USUARIO_INSERCAO  		   varchar2(30) CONSTRAINT NN_USUARIO_POSTO_TRABALHO3 NOT NULL,
  DATA_INSERCAO     		   timestamp  CONSTRAINT NN_USUARIO_POSTO_TRABALHO4 NOT NULL,
  USUARIO_ALTERACAO 		   varchar2(30),
  DATA_ALTERACAO    		   timestamp,
  REGISTRO_EXCLUIDO 		   char(1) default 'N' CONSTRAINT NN_USUARIO_POSTO_TRABALHO5 NOT NULL,
  USUARIO_EXCLUSAO  		   varchar2(30),
  DATA_EXCLUSAO     		   timestamp
 );
 
ALTER TABLE SEFAZ_SEG.TA_USUARIO_POSTO_TRABALHO ADD CONSTRAINT CK_USUARIO_POSTO_TRABALHO1 CHECK (REGISTRO_EXCLUIDO IN ('S', 'N')); 
  
COMMENT ON TABLE SEFAZ_SEG.TA_USUARIO_POSTO_TRABALHO IS 'Tabela com os usuários por posto de trabalho';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_POSTO_TRABALHO.IDENTIFICACAO_POSTO_TRABALHO IS 'Identificação do Posto do Trabalho';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_POSTO_TRABALHO.CPF_USUARIO IS 'Usuário do sistema (Funcionário SEFAZ)';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_POSTO_TRABALHO.USUARIO_INSERCAO IS 'Usuário inserção do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_POSTO_TRABALHO.DATA_INSERCAO IS 'Data - hora inserção do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_POSTO_TRABALHO.USUARIO_ALTERACAO IS 'Usuário alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_POSTO_TRABALHO.DATA_ALTERACAO IS 'Data - hora alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_POSTO_TRABALHO.REGISTRO_EXCLUIDO IS 'Identificador do registro excluido (S) Sim ou (N) Não';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_POSTO_TRABALHO.USUARIO_EXCLUSAO IS 'Usuário que fez a exclusão';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_POSTO_TRABALHO.DATA_EXCLUSAO IS 'Data - hora exclusão do registro';


CREATE TABLE SEFAZ_SEG.TA_USUARIO_PRINCIPAL_EMPRESA (
  IDENTIFICACAO_USUARIO_PRINCIP number(10) CONSTRAINT NN_USUARIO_PRINCIPAL_EMPRESA1 NOT NULL, 
  CNPJ_EMPRESA                  varchar2(20) CONSTRAINT NN_USUARIO_PRINCIPAL_EMPRESA2 NOT NULL, 
  CPF_USUARIO                   varchar2(11) CONSTRAINT NN_USUARIO_PRINCIPAL_EMPRESA3 NOT NULL, 
  USUARIO_INSERCAO              varchar2(30) CONSTRAINT NN_USUARIO_PRINCIPAL_EMPRESA4 NOT NULL, 
  DATA_INSERCAO                 timestamp CONSTRAINT NN_USUARIO_PRINCIPAL_EMPRESA5 NOT NULL,
  USUARIO_ALTERACAO 		    varchar2(30),
  DATA_ALTERACAO    		    timestamp,
  REGISTRO_EXCLUIDO             char(1) DEFAULT 'N' CONSTRAINT NN_USUARIO_PRINCIPAL_EMPRESA6 NOT NULL, 
  USUARIO_EXCLUSAO              varchar2(30), 
  DATA_EXCLUSAO                 timestamp
);
  
ALTER TABLE SEFAZ_SEG.TA_USUARIO_PRINCIPAL_EMPRESA ADD CONSTRAINT PK_USUARIO_PRINCIPAL_EMPRESA PRIMARY KEY (IDENTIFICACAO_USUARIO_PRINCIP);
ALTER TABLE SEFAZ_SEG.TA_USUARIO_PRINCIPAL_EMPRESA ADD CONSTRAINT CK_USUARIO_PRINCIPAL_EMPRESA1 CHECK (REGISTRO_EXCLUIDO IN ('S', 'N'));
  
COMMENT ON TABLE SEFAZ_SEG.TA_USUARIO_PRINCIPAL_EMPRESA IS 'Tabela que tem os usuários principais da uma empresa';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_PRINCIPAL_EMPRESA.IDENTIFICACAO_USUARIO_PRINCIP IS 'Identificação do usuario principal para uma empresa';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_PRINCIPAL_EMPRESA.CNPJ_EMPRESA IS 'CNPJ empresa';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_PRINCIPAL_EMPRESA.CPF_USUARIO IS 'CPF usuário principal';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_PRINCIPAL_EMPRESA.USUARIO_INSERCAO IS 'Usuário inserção do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_PRINCIPAL_EMPRESA.DATA_INSERCAO IS 'Data - hora inserção';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_PRINCIPAL_EMPRESA.USUARIO_ALTERACAO IS 'Usuário alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_PRINCIPAL_EMPRESA.DATA_ALTERACAO IS 'Data - hora alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_PRINCIPAL_EMPRESA.REGISTRO_EXCLUIDO IS 'Indicador do registro excluido (S) Sim ou (N) Não';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_PRINCIPAL_EMPRESA.USUARIO_EXCLUSAO IS 'Usuário exclusão';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_PRINCIPAL_EMPRESA.DATA_EXCLUSAO IS 'Data - hora exclusão';

CREATE TABLE SEFAZ_SEG.TA_PROCURACAO_USUARIO (
  IDENTIFICACAO_PROCUR_USUARIO number(10) CONSTRAINT NN_PROCURACAO_USUARIO1 NOT NULL, 
  CPF_ORIGEM                   varchar2(11), 
  CNPJ_ORIGEM                  varchar2(20), 
  CPF_PROCURADO                varchar2(11), 
  USUARIO_INSERCAO             varchar2(30) CONSTRAINT NN_PROCURACAO_USUARIO2 NOT NULL, 
  DATA_INSERCAO                timestamp  CONSTRAINT NN_PROCURACAO_USUARIO3 NOT NULL, 
  USUARIO_ALTERACAO            varchar2(30), 
  DATA_ALTERACAO               timestamp, 
  REGISTRO_EXCLUIDO            char(1) default 'N' CONSTRAINT NN_PROCURACAO_USUARIO4 NOT NULL, 
  USUARIO_EXCLUSAO             varchar2(30), 
  DATA_EXCLUSAO                timestamp
);
  
ALTER TABLE SEFAZ_SEG.TA_PROCURACAO_USUARIO ADD CONSTRAINT PK_PROCURACAO_USUARIO PRIMARY KEY (IDENTIFICACAO_PROCUR_USUARIO);
ALTER TABLE SEFAZ_SEG.TA_PROCURACAO_USUARIO ADD CONSTRAINT CK_PROCURACAO_USUARIO1 CHECK (REGISTRO_EXCLUIDO IN ('S', 'N'));

COMMENT ON TABLE SEFAZ_SEG.TA_PROCURACAO_USUARIO IS 'Tabela com os usuários procurados';
COMMENT ON COLUMN SEFAZ_SEG.TA_PROCURACAO_USUARIO.IDENTIFICACAO_PROCUR_USUARIO IS 'Identificação do procurado por usuario';
COMMENT ON COLUMN SEFAZ_SEG.TA_PROCURACAO_USUARIO.CPF_ORIGEM IS 'CPF Contribuinte Origem';
COMMENT ON COLUMN SEFAZ_SEG.TA_PROCURACAO_USUARIO.CNPJ_ORIGEM IS 'CNPJ da Empresa Origem';
COMMENT ON COLUMN SEFAZ_SEG.TA_PROCURACAO_USUARIO.CPF_PROCURADO IS 'CPF do usuário procurado para atuar en nome de um contribuinte';
COMMENT ON COLUMN SEFAZ_SEG.TA_PROCURACAO_USUARIO.USUARIO_INSERCAO IS 'Usuário inserção do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_PROCURACAO_USUARIO.DATA_INSERCAO IS 'Data - hora inserção do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_PROCURACAO_USUARIO.USUARIO_ALTERACAO IS 'Usuário alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_PROCURACAO_USUARIO.DATA_ALTERACAO IS 'Data - hora alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_PROCURACAO_USUARIO.REGISTRO_EXCLUIDO IS 'Identificador do registro excluido (S) Sim ou (N) Não';
COMMENT ON COLUMN SEFAZ_SEG.TA_PROCURACAO_USUARIO.USUARIO_EXCLUSAO IS 'Usuário que fez a exclusão';
COMMENT ON COLUMN SEFAZ_SEG.TA_PROCURACAO_USUARIO.DATA_EXCLUSAO IS 'Data - hora exclusão do registro';


CREATE TABLE SEFAZ_SEG.TA_PROCURACAO_OPCAO (
  IDENTIFICACAO_PROCURADO_OPCAO number(10) CONSTRAINT NN_PROCURACAO_OPCAO1 NOT NULL, 
  IDENTIFICACAO_PROCUR_USUARIO  number(10) CONSTRAINT NN_PROCURACAO_OPCAO2 NOT NULL, 
  IDENTIFICACAO_OPCAO_APLICACAO number(10) CONSTRAINT NN_PROCURACAO_OPCAO3 NOT NULL, 
  USUARIO_INSERCAO              varchar2(30) CONSTRAINT NN_PROCURACAO_OPCAO4 NOT NULL, 
  DATA_INSERCAO                 timestamp CONSTRAINT NN_PROCURACAO_OPCAO5 NOT NULL,
  USUARIO_ALTERACAO             varchar2(30), 
  DATA_ALTERACAO                timestamp, 
  REGISTRO_EXCLUIDO             char(1) DEFAULT 'N' CONSTRAINT NN_PROCURACAO_OPCAO6 NOT NULL, 
  USUARIO_EXCLUSAO              varchar2(30), 
  DATA_EXCLUSAO                 timestamp
);
  
ALTER TABLE SEFAZ_SEG.TA_PROCURACAO_OPCAO ADD CONSTRAINT PK_PROCURACAO_OPCAO PRIMARY KEY (IDENTIFICACAO_PROCURADO_OPCAO);
ALTER TABLE SEFAZ_SEG.TA_PROCURACAO_OPCAO ADD CONSTRAINT CK_PROCURACAO_OPCAO1 CHECK (REGISTRO_EXCLUIDO IN ('S', 'N'));
 
COMMENT ON TABLE SEFAZ_SEG.TA_PROCURACAO_OPCAO IS 'Tabela com a procuração das opções do sistema, nesta tabela não existe alteração só pode criar o excluir registros';
COMMENT ON COLUMN SEFAZ_SEG.TA_PROCURACAO_OPCAO.IDENTIFICACAO_PROCURADO_OPCAO IS 'Identificação das opções procuradas para os usuários';
COMMENT ON COLUMN SEFAZ_SEG.TA_PROCURACAO_OPCAO.IDENTIFICACAO_PROCUR_USUARIO IS 'Identificação usuário procurado';
COMMENT ON COLUMN SEFAZ_SEG.TA_PROCURACAO_OPCAO.IDENTIFICACAO_OPCAO_APLICACAO IS 'Identificação do opção do sistema';
COMMENT ON COLUMN SEFAZ_SEG.TA_PROCURACAO_OPCAO.USUARIO_INSERCAO IS 'Usuário que fez a inserção do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_PROCURACAO_OPCAO.DATA_INSERCAO IS 'Data - hora inserção do regsitro';
COMMENT ON COLUMN SEFAZ_SEG.TA_PROCURACAO_OPCAO.USUARIO_ALTERACAO IS 'Usuário alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_PROCURACAO_OPCAO.DATA_ALTERACAO IS 'Data - hora alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_PROCURACAO_OPCAO.REGISTRO_EXCLUIDO IS 'Indicador do Registro Excluido';
COMMENT ON COLUMN SEFAZ_SEG.TA_PROCURACAO_OPCAO.USUARIO_EXCLUSAO IS 'Usuário que fez a exclusão';
COMMENT ON COLUMN SEFAZ_SEG.TA_PROCURACAO_OPCAO.DATA_EXCLUSAO IS 'Data - hora exclusão registro';

CREATE TABLE SEFAZ_SEG.TA_SOLICITACAO_USUARIO (
  IDENTIFICACAO_SOLICITACAO  number(10) CONSTRAINT NN_SOLICITACAO_USUARIO1 NOT NULL, 
  CPF                        varchar2(11) CONSTRAINT NN_SOLICITACAO_USUARIO2 NOT NULL, 
  CNPJ_NEGOCIO               varchar2(30) CONSTRAINT NN_SOLICITACAO_USUARIO3 NOT NULL, 
  INSCRICAO_ESTADUAL_NEGOCIO varchar2(30) CONSTRAINT NN_SOLICITACAO_USUARIO4 NOT NULL, 
  SITUACAO_SOLICITACAO       char(1) CONSTRAINT NN_SOLICITACAO_USUARIO5 NOT NULL, 
  USUARIO_INSERCAO           varchar2(30) CONSTRAINT NN_SOLICITACAO_USUARIO6 NOT NULL, 
  DATA_INSERCAO              timestamp CONSTRAINT NN_SOLICITACAO_USUARIO7 NOT NULL, 
  USUARIO_ALTERACAO          varchar2(30), 
  DATA_ALTERACAO             timestamp, 
  REGISTRO_EXCLUIDO          char(1) DEFAULT 'N' CONSTRAINT NN_SOLICITACAO_USUARIO8 NOT NULL, 
  USUARIO_EXCLUSAO           varchar2(30), 
  DATA_EXCLUSAO              timestamp
  );
  
ALTER TABLE SEFAZ_SEG.TA_SOLICITACAO_USUARIO ADD CONSTRAINT PK_SOLICITACAO_USUARIO PRIMARY KEY (IDENTIFICACAO_SOLICITACAO);
ALTER TABLE SEFAZ_SEG.TA_SOLICITACAO_USUARIO ADD CONSTRAINT CK_SOLICITACAO_USUARIO1 CHECK (SITUACAO_SOLICITACAO IN ('P','C'));
ALTER TABLE SEFAZ_SEG.TA_SOLICITACAO_USUARIO ADD CONSTRAINT CK_SOLICITACAO_USUARIO2 CHECK (REGISTRO_EXCLUIDO IN ('S','N'));


COMMENT ON TABLE SEFAZ_SEG.TA_SOLICITACAO_USUARIO IS 'Tabela com as solicitações impresas do autorização de senhas para o sistema';
COMMENT ON COLUMN SEFAZ_SEG.TA_SOLICITACAO_USUARIO.IDENTIFICACAO_SOLICITACAO IS 'Identificação da solicitação de senhas';
COMMENT ON COLUMN SEFAZ_SEG.TA_SOLICITACAO_USUARIO.CPF IS 'CPF da solicitação';
COMMENT ON COLUMN SEFAZ_SEG.TA_SOLICITACAO_USUARIO.CNPJ_NEGOCIO IS 'CNPJ da empresa associado a CPF';
COMMENT ON COLUMN SEFAZ_SEG.TA_SOLICITACAO_USUARIO.INSCRICAO_ESTADUAL_NEGOCIO IS 'Inscrição Estadual da empresa associada ao CPF';
COMMENT ON COLUMN SEFAZ_SEG.TA_SOLICITACAO_USUARIO.SITUACAO_SOLICITACAO IS 'Situação da Solcitiação de autorização de senhas (P) Pendente, (C) Criado';
COMMENT ON COLUMN SEFAZ_SEG.TA_SOLICITACAO_USUARIO.USUARIO_INSERCAO IS 'Usuário inserção do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_SOLICITACAO_USUARIO.DATA_INSERCAO IS 'Data - hora inserção do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_SOLICITACAO_USUARIO.USUARIO_ALTERACAO IS 'Usuário alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_SOLICITACAO_USUARIO.DATA_ALTERACAO IS 'Data - hora alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_SOLICITACAO_USUARIO.REGISTRO_EXCLUIDO IS 'Identificador do registro excluido (S) Sim ou (N) Não';
COMMENT ON COLUMN SEFAZ_SEG.TA_SOLICITACAO_USUARIO.USUARIO_EXCLUSAO IS 'Uusuário que fez a exclusão';
COMMENT ON COLUMN SEFAZ_SEG.TA_SOLICITACAO_USUARIO.DATA_EXCLUSAO IS 'Data - hora exclusão do regsitro';


CREATE TABLE SEFAZ_SEG.TA_POSTO_TRABALHO (
  IDENTIFICACAO_POSTO_TRABALHO number(10) CONSTRAINT NN_POSTO_TRABALHO1 NOT NULL, 
  NOME_POSTO_TRABALHO          varchar2(100) CONSTRAINT NN_POSTO_TRABALHO2 NOT NULL, 
  IDENTIFICACAO_UNID_ORGANIZAC number(10) CONSTRAINT NN_POSTO_TRABALHO3 NOT NULL, 
  USUARIO_INSERCAO             varchar2(30) CONSTRAINT NN_POSTO_TRABALHO4 NOT NULL, 
  DATA_INSERCAO                timestamp CONSTRAINT NN_POSTO_TRABALHO5 NOT NULL, 
  USUARIO_ALTERACAO            varchar2(30), 
  DATA_ALTERACAO               timestamp, 
  REGISTRO_EXCLUIDO            char(1) DEFAULT 'N' CONSTRAINT NN_POSTO_TRABALHO6 NOT NULL, 
  USUARIO_EXCLUSAO             varchar2(30), 
  DATA_EXCLUSAO                timestamp
);
  
ALTER TABLE SEFAZ_SEG.TA_POSTO_TRABALHO ADD CONSTRAINT PK_POSTO_TRABALHO PRIMARY KEY (IDENTIFICACAO_POSTO_TRABALHO);
ALTER TABLE SEFAZ_SEG.TA_POSTO_TRABALHO ADD CONSTRAINT CK_POSTO_TRABALHO1 CHECK (REGISTRO_EXCLUIDO IN ('S','N'));
  
COMMENT ON TABLE SEFAZ_SEG.TA_POSTO_TRABALHO IS 'Tabela dos postos de trabalho da SEFAZ-TO';
COMMENT ON COLUMN SEFAZ_SEG.TA_POSTO_TRABALHO.NOME_POSTO_TRABALHO IS 'Nome do Posto de Trabalho';
COMMENT ON COLUMN SEFAZ_SEG.TA_POSTO_TRABALHO.IDENTIFICACAO_UNID_ORGANIZAC IS 'Identificação da Unidade Organizacional';
COMMENT ON COLUMN SEFAZ_SEG.TA_POSTO_TRABALHO.USUARIO_INSERCAO IS 'Usuario Inserção do Registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_POSTO_TRABALHO.DATA_INSERCAO IS 'Data - hora inserção do regsitro';
COMMENT ON COLUMN SEFAZ_SEG.TA_POSTO_TRABALHO.USUARIO_ALTERACAO IS 'Usuario  alteração do sistema';
COMMENT ON COLUMN SEFAZ_SEG.TA_POSTO_TRABALHO.DATA_ALTERACAO IS 'Data - hora alteração';
COMMENT ON COLUMN SEFAZ_SEG.TA_POSTO_TRABALHO.REGISTRO_EXCLUIDO IS 'Indicador se o registro está excluido logicamente (S) Sim ou (N) Não';
COMMENT ON COLUMN SEFAZ_SEG.TA_POSTO_TRABALHO.USUARIO_EXCLUSAO IS 'Usuário exclusão do regsitro';
COMMENT ON COLUMN SEFAZ_SEG.TA_POSTO_TRABALHO.DATA_EXCLUSAO IS 'Data - hora exclusão';


CREATE TABLE SEFAZ_SEG.TA_UNIDADE_ORGANIZACIONAL (
  IDENTIFICACAO_UNID_ORGANIZAC number(10) CONSTRAINT NN_UNIDADE_ORGANIZACIONAL1 NOT NULL, 
  NOME_UNID_ORGANIZAC          varchar2(100) CONSTRAINT NN_UNIDADE_ORGANIZACIONAL2 NOT NULL, 
  UNID_ORGANIZAC_PAI           number(10), 
  TELEFONE                     varchar2(30), 
  ENDERECO                     varchar2(100), 
  CHEFE_GERAL                  varchar2(60), 
  USUARIO_INSERCAO             varchar2(30) CONSTRAINT NN_UNIDADE_ORGANIZACIONAL3 NOT NULL, 
  DATA_INSERCAO                timestamp CONSTRAINT NN_UNIDADE_ORGANIZACIONAL4 NOT NULL, 
  USUARIO_ALTERACAO            varchar2(30), 
  DATA_ALTERACAO               timestamp, 
  REGISTRO_EXCLUIDO            char(1) DEFAULT 'N' CONSTRAINT NN_UNIDADE_ORGANIZACIONAL5 NOT NULL, 
  USUARIO_EXCLUSAO             varchar2(30), 
  DATA_EXCLUSAO                timestamp
);
  
ALTER TABLE SEFAZ_SEG.TA_UNIDADE_ORGANIZACIONAL ADD CONSTRAINT PK_UNIDADE_ORGANIZACIONAL PRIMARY KEY (IDENTIFICACAO_UNID_ORGANIZAC);
ALTER TABLE SEFAZ_SEG.TA_UNIDADE_ORGANIZACIONAL ADD CONSTRAINT CK_UNIDADE_ORGANIZACIONAL1 CHECK (REGISTRO_EXCLUIDO IN ('S','N'));
  
COMMENT ON TABLE SEFAZ_SEG.TA_UNIDADE_ORGANIZACIONAL IS 'Tabela com as unidades prganizacionais da SEFAZ-TO';
COMMENT ON COLUMN SEFAZ_SEG.TA_UNIDADE_ORGANIZACIONAL.IDENTIFICACAO_UNID_ORGANIZAC IS 'Identificação da Unidade Organizacional';
COMMENT ON COLUMN SEFAZ_SEG.TA_UNIDADE_ORGANIZACIONAL.NOME_UNID_ORGANIZAC IS 'Nome da Unidade Organizacional';
COMMENT ON COLUMN SEFAZ_SEG.TA_UNIDADE_ORGANIZACIONAL.UNID_ORGANIZAC_PAI IS 'Unidade Organizacional Pai';
COMMENT ON COLUMN SEFAZ_SEG.TA_UNIDADE_ORGANIZACIONAL.TELEFONE IS 'Telefone da Unidade Organizacional';
COMMENT ON COLUMN SEFAZ_SEG.TA_UNIDADE_ORGANIZACIONAL.ENDERECO IS 'Endereço da Unidade Organizacional';
COMMENT ON COLUMN SEFAZ_SEG.TA_UNIDADE_ORGANIZACIONAL.CHEFE_GERAL IS 'Nome do Chefe da Unidade Organizacional';
COMMENT ON COLUMN SEFAZ_SEG.TA_UNIDADE_ORGANIZACIONAL.USUARIO_INSERCAO IS 'Usuário Inserção do Registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_UNIDADE_ORGANIZACIONAL.DATA_INSERCAO IS 'Data - hora Inserção do Registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_UNIDADE_ORGANIZACIONAL.USUARIO_ALTERACAO IS 'Usuário que fez alguma alteração no registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_UNIDADE_ORGANIZACIONAL.DATA_ALTERACAO IS 'Data - hora alteração';
COMMENT ON COLUMN SEFAZ_SEG.TA_UNIDADE_ORGANIZACIONAL.REGISTRO_EXCLUIDO IS 'Identificador do registro excluido';
COMMENT ON COLUMN SEFAZ_SEG.TA_UNIDADE_ORGANIZACIONAL.USUARIO_EXCLUSAO IS 'Usuário que fez a exclusão';
COMMENT ON COLUMN SEFAZ_SEG.TA_UNIDADE_ORGANIZACIONAL.DATA_EXCLUSAO IS 'Data - hora exclusão';


CREATE TABLE SEFAZ_SEG.TA_SMS_CONTRIBUINTE (
  IDENTIFICACAO_SMS_ENVIADO number(10) CONSTRAINT NN_SMS_CONTRIBUINTE1 NOT NULL, 
  CPF_DESTINATARIO          varchar2(11) CONSTRAINT NN_SMS_CONTRIBUINTE2 NOT NULL, 
  NUMERO_TELEFONE           varchar2(12) CONSTRAINT NN_SMS_CONTRIBUINTE3 NOT NULL, 
  DATA_ENVIO                timestamp CONSTRAINT NN_SMS_CONTRIBUINTE4 NOT NULL, 
  ASSUNTO                   varchar2(30) CONSTRAINT NN_SMS_CONTRIBUINTE5 NOT NULL, 
  CONTEUDO                  varchar2(100) CONSTRAINT NN_SMS_CONTRIBUINTE6 NOT NULL, 
  USUARIO_INSERCAO          varchar2(30) CONSTRAINT NN_SMS_CONTRIBUINTE7 NOT NULL, 
  DATA_INSERCAO             timestamp CONSTRAINT NN_SMS_CONTRIBUINTE8 NOT NULL, 
  USUARIO_ALTERACAO         varchar2(30), 
  DATA_ALTERACAO            timestamp, 
  REGISTRO_EXCLUIDO         char(1) DEFAULT 'N' CONSTRAINT NN_SMS_CONTRIBUINTE9 NOT NULL, 
  USUARIO_EXCLUSAO          varchar2(30), 
  DATA_EXCLUSAO             timestamp
);
  
ALTER TABLE SEFAZ_SEG.TA_SMS_CONTRIBUINTE ADD CONSTRAINT PK_SMS_CONTRIBUINTE PRIMARY KEY (IDENTIFICACAO_SMS_ENVIADO);
ALTER TABLE SEFAZ_SEG.TA_SMS_CONTRIBUINTE ADD CONSTRAINT CK_SMS_CONTRIBUINTE1 CHECK (REGISTRO_EXCLUIDO IN ('S','N'));


COMMENT ON TABLE SEFAZ_SEG.TA_SMS_CONTRIBUINTE IS 'Tabela com os registros das mensagems SMS enviadas para os usuários do sistema';
COMMENT ON COLUMN SEFAZ_SEG.TA_SMS_CONTRIBUINTE.IDENTIFICACAO_SMS_ENVIADO IS 'Identificação sequêncial para as mensagems SMS';
COMMENT ON COLUMN SEFAZ_SEG.TA_SMS_CONTRIBUINTE.CPF_DESTINATARIO IS 'CPF do destinatario do SMS';
COMMENT ON COLUMN SEFAZ_SEG.TA_SMS_CONTRIBUINTE.NUMERO_TELEFONE IS 'Número de Telefone onde foi enviado o SMS';
COMMENT ON COLUMN SEFAZ_SEG.TA_SMS_CONTRIBUINTE.DATA_ENVIO IS 'Data - hora de envio do SMS';
COMMENT ON COLUMN SEFAZ_SEG.TA_SMS_CONTRIBUINTE.ASSUNTO IS 'Assunto da mensagem SMS';
COMMENT ON COLUMN SEFAZ_SEG.TA_SMS_CONTRIBUINTE.CONTEUDO IS 'Conteúdo da mensagem SMS';
COMMENT ON COLUMN SEFAZ_SEG.TA_SMS_CONTRIBUINTE.USUARIO_INSERCAO IS 'Usuário inserção do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_SMS_CONTRIBUINTE.DATA_INSERCAO IS 'Data - hora inserção';
COMMENT ON COLUMN SEFAZ_SEG.TA_SMS_CONTRIBUINTE.USUARIO_ALTERACAO IS 'Usuário alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_SMS_CONTRIBUINTE.DATA_ALTERACAO IS 'Data - hora alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_SMS_CONTRIBUINTE.REGISTRO_EXCLUIDO IS 'Indicador para registro excluido (S) Sim ou (N) Não';
COMMENT ON COLUMN SEFAZ_SEG.TA_SMS_CONTRIBUINTE.USUARIO_EXCLUSAO IS 'Usuário que fez a exclusão do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_SMS_CONTRIBUINTE.DATA_EXCLUSAO IS 'Data - hora exclusão';


CREATE TABLE SEFAZ_SEG.TA_HISTORICO_LOGIN_SISTEMA (
  IDENTIFICACAO_LOGIN_SISTEMA number(10) CONSTRAINT NN_HISTORICO_LOGIN_SISTEMA1 NOT NULL, 
  CPF_USUARIO                 varchar2(11) CONSTRAINT NN_HISTORICO_LOGIN_SISTEMA2 NOT NULL, 
  DATA_HORA_LOGIN             timestamp CONSTRAINT NN_HISTORICO_LOGIN_SISTEMA3 NOT NULL,
  USUARIO_INSERCAO            varchar2(30) CONSTRAINT NN_HISTORICO_LOGIN_SISTEMA4 NOT NULL, 
  DATA_INSERCAO               timestamp CONSTRAINT NN_HISTORICO_LOGIN_SISTEMA5 NOT NULL, 
  USUARIO_ALTERACAO           varchar2(30), 
  DATA_ALTERACAO              timestamp, 
  REGISTRO_EXCLUIDO           char(1) DEFAULT 'N' CONSTRAINT NN_HISTORICO_LOGIN_SISTEMA6 NOT NULL, 
  USUARIO_EXCLUSAO            varchar2(30), 
  DATA_EXCLUSAO               timestamp
);
  
ALTER TABLE SEFAZ_SEG.TA_HISTORICO_LOGIN_SISTEMA ADD CONSTRAINT PK_HISTORICO_LOGIN_SISTEMA PRIMARY KEY (IDENTIFICACAO_LOGIN_SISTEMA);
ALTER TABLE SEFAZ_SEG.TA_HISTORICO_LOGIN_SISTEMA ADD CONSTRAINT CK_HISTORICO_LOGIN_SISTEMA1 CHECK (REGISTRO_EXCLUIDO IN ('S','N'));
  
COMMENT ON TABLE SEFAZ_SEG.TA_HISTORICO_LOGIN_SISTEMA IS 'Tabela que salva os logins históricos do sistema pelos usuários';
COMMENT ON COLUMN SEFAZ_SEG.TA_HISTORICO_LOGIN_SISTEMA.IDENTIFICACAO_LOGIN_SISTEMA IS 'Identificação sequêncial do login do sistema';
COMMENT ON COLUMN SEFAZ_SEG.TA_HISTORICO_LOGIN_SISTEMA.CPF_USUARIO IS 'CPF do usuário';
COMMENT ON COLUMN SEFAZ_SEG.TA_HISTORICO_LOGIN_SISTEMA.DATA_HORA_LOGIN IS 'data/hora acesso';
COMMENT ON COLUMN SEFAZ_SEG.TA_HISTORICO_LOGIN_SISTEMA.USUARIO_INSERCAO IS 'Usuário inserção do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_HISTORICO_LOGIN_SISTEMA.DATA_INSERCAO IS 'Data - hora inserção';
COMMENT ON COLUMN SEFAZ_SEG.TA_HISTORICO_LOGIN_SISTEMA.USUARIO_ALTERACAO IS 'Usuário alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_HISTORICO_LOGIN_SISTEMA.DATA_ALTERACAO IS 'Data - hora alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_HISTORICO_LOGIN_SISTEMA.REGISTRO_EXCLUIDO IS 'Indicador para registro excluido (S) Sim ou (N) Não';
COMMENT ON COLUMN SEFAZ_SEG.TA_HISTORICO_LOGIN_SISTEMA.USUARIO_EXCLUSAO IS 'Usuário que fez a exclusão do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_HISTORICO_LOGIN_SISTEMA.DATA_EXCLUSAO IS 'Data - hora exclusão';


CREATE TABLE SEFAZ_SEG.TA_PAPEL_OPCAO (
  IDENTIFICACAO_OPCAO_APLICACAO number(10) CONSTRAINT NN_PAPEL_OPCAO1 NOT NULL, 
  IDENTIFICACAO_PAPEL           number(10) CONSTRAINT NN_PAPEL_OPCAO2 NOT NULL,
  USUARIO_INSERCAO              varchar2(30) CONSTRAINT NN_PAPEL_OPCAO3 NOT NULL, 
  DATA_INSERCAO                 timestamp CONSTRAINT NN_PAPEL_OPCAO4 NOT NULL, 
  USUARIO_ALTERACAO             varchar2(30), 
  DATA_ALTERACAO                timestamp, 
  REGISTRO_EXCLUIDO             char(1) DEFAULT 'N' CONSTRAINT NN_PAPEL_OPCAO5 NOT NULL, 
  USUARIO_EXCLUSAO              varchar2(30), 
  DATA_EXCLUSAO                 timestamp
);
  
ALTER TABLE SEFAZ_SEG.TA_PAPEL_OPCAO ADD CONSTRAINT PK_PAPEL_OPCAO PRIMARY KEY (IDENTIFICACAO_OPCAO_APLICACAO, IDENTIFICACAO_PAPEL);
ALTER TABLE SEFAZ_SEG.TA_PAPEL_OPCAO ADD CONSTRAINT CK_PAPEL_OPCAO1 CHECK (REGISTRO_EXCLUIDO IN ('S','N'));

COMMENT ON TABLE SEFAZ_SEG.TA_PAPEL_OPCAO IS 'Tabela para associar o papel com as opções disponíveis';
COMMENT ON COLUMN SEFAZ_SEG.TA_PAPEL_OPCAO.IDENTIFICACAO_OPCAO_APLICACAO IS 'Identificação da opção por aplicativo';
COMMENT ON COLUMN SEFAZ_SEG.TA_PAPEL_OPCAO.IDENTIFICACAO_PAPEL IS 'Identificação do Papel associado ao opção';
COMMENT ON COLUMN SEFAZ_SEG.TA_PAPEL_OPCAO.USUARIO_INSERCAO IS 'Usuário inserção do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_PAPEL_OPCAO.DATA_INSERCAO IS 'Data - hora inserção';
COMMENT ON COLUMN SEFAZ_SEG.TA_PAPEL_OPCAO.USUARIO_ALTERACAO IS 'Usuário alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_PAPEL_OPCAO.DATA_ALTERACAO IS 'Data - hora alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_PAPEL_OPCAO.REGISTRO_EXCLUIDO IS 'Indicador para registro excluido (S) Sim ou (N) Não';
COMMENT ON COLUMN SEFAZ_SEG.TA_PAPEL_OPCAO.USUARIO_EXCLUSAO IS 'Usuário que fez a exclusão do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_PAPEL_OPCAO.DATA_EXCLUSAO IS 'Data - hora exclusão';


CREATE TABLE SEFAZ_SEG.TA_PERFIL_PAPEL (
  IDENTIFICACAO_PERFIL 		  number(10) CONSTRAINT NN_PERFIL_PAPEL1 NOT NULL, 
  IDENTIFICACAO_PAPEL  		  number(10) CONSTRAINT NN_PERFIL_PAPEL2 NOT NULL,
  USUARIO_INSERCAO            varchar2(30) CONSTRAINT NN_PERFIL_PAPEL3 NOT NULL, 
  DATA_INSERCAO               timestamp CONSTRAINT NN_PERFIL_PAPEL4 NOT NULL, 
  USUARIO_ALTERACAO           varchar2(30), 
  DATA_ALTERACAO              timestamp, 
  REGISTRO_EXCLUIDO           char(1) DEFAULT 'N' CONSTRAINT NN_PERFIL_PAPEL5 NOT NULL, 
  USUARIO_EXCLUSAO            varchar2(30), 
  DATA_EXCLUSAO               timestamp
);
  
ALTER TABLE SEFAZ_SEG.TA_PERFIL_PAPEL ADD CONSTRAINT PK_PERFIL_PAPEL PRIMARY KEY (IDENTIFICACAO_PERFIL,IDENTIFICACAO_PAPEL);
ALTER TABLE SEFAZ_SEG.TA_PERFIL_PAPEL ADD CONSTRAINT CK_PERFIL_PAPEL1 CHECK (REGISTRO_EXCLUIDO IN ('S','N'));
  
COMMENT ON TABLE SEFAZ_SEG.TA_PERFIL_PAPEL IS 'Tabela dos perfis associado aos papeis (roles)';
COMMENT ON COLUMN SEFAZ_SEG.TA_PERFIL_PAPEL.IDENTIFICACAO_PERFIL IS 'Identificação do perfil';
COMMENT ON COLUMN SEFAZ_SEG.TA_PERFIL_PAPEL.IDENTIFICACAO_PAPEL IS 'Identificação do papel';
COMMENT ON COLUMN SEFAZ_SEG.TA_PERFIL_PAPEL.USUARIO_INSERCAO IS 'Usuário inserção do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_PERFIL_PAPEL.DATA_INSERCAO IS 'Data - hora inserção';
COMMENT ON COLUMN SEFAZ_SEG.TA_PERFIL_PAPEL.USUARIO_ALTERACAO IS 'Usuário alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_PERFIL_PAPEL.DATA_ALTERACAO IS 'Data - hora alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_PERFIL_PAPEL.REGISTRO_EXCLUIDO IS 'Indicador para registro excluido (S) Sim ou (N) Não';
COMMENT ON COLUMN SEFAZ_SEG.TA_PERFIL_PAPEL.USUARIO_EXCLUSAO IS 'Usuário que fez a exclusão do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_PERFIL_PAPEL.DATA_EXCLUSAO IS 'Data - hora exclusão';


CREATE TABLE SEFAZ_SEG.TA_PAPEL_SISTEMA (
  IDENTIFICACAO_PAPEL number(10) CONSTRAINT NN_PAPEL_SISTEMA1 NOT NULL, 
  NOME_PAPEL          varchar2(30) CONSTRAINT NN_PAPEL_SISTEMA2 NOT NULL, 
  DESCRICAO_PAPEL     varchar2(120) CONSTRAINT NN_PAPEL_SISTEMA3 NOT NULL,
  USUARIO_INSERCAO    varchar2(30) CONSTRAINT NN_PAPEL_SISTEMA4 NOT NULL, 
  DATA_INSERCAO       timestamp CONSTRAINT NN_PAPEL_SISTEMA5 NOT NULL, 
  USUARIO_ALTERACAO   varchar2(30), 
  DATA_ALTERACAO      timestamp, 
  REGISTRO_EXCLUIDO   char(1) DEFAULT 'N'  CONSTRAINT NN_PAPEL_SISTEMA6 NOT NULL, 
  USUARIO_EXCLUSAO    varchar2(30), 
  DATA_EXCLUSAO       timestamp
);

ALTER TABLE SEFAZ_SEG.TA_PAPEL_SISTEMA ADD CONSTRAINT PK_PAPEL_SISTEMA PRIMARY KEY (IDENTIFICACAO_PAPEL);
ALTER TABLE SEFAZ_SEG.TA_PAPEL_SISTEMA ADD CONSTRAINT CK_PAPEL_SISTEMA1 CHECK (REGISTRO_EXCLUIDO IN ('S','N'));
  
COMMENT ON TABLE SEFAZ_SEG.TA_PAPEL_SISTEMA IS 'Tabela para cadastrar os papeis do sistema';
COMMENT ON COLUMN SEFAZ_SEG.TA_PAPEL_SISTEMA.IDENTIFICACAO_PAPEL IS 'Identificação do papel do sistema';
COMMENT ON COLUMN SEFAZ_SEG.TA_PAPEL_SISTEMA.NOME_PAPEL IS 'Nome do papel do sistema';
COMMENT ON COLUMN SEFAZ_SEG.TA_PAPEL_SISTEMA.DESCRICAO_PAPEL IS 'Descrição do papel';
COMMENT ON COLUMN SEFAZ_SEG.TA_PAPEL_SISTEMA.USUARIO_INSERCAO IS 'Usuário inserção do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_PAPEL_SISTEMA.DATA_INSERCAO IS 'Data - hora inserção';
COMMENT ON COLUMN SEFAZ_SEG.TA_PAPEL_SISTEMA.USUARIO_ALTERACAO IS 'Usuário alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_PAPEL_SISTEMA.DATA_ALTERACAO IS 'Data - hora alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_PAPEL_SISTEMA.REGISTRO_EXCLUIDO IS 'Indicador para registro excluido (S) Sim ou (N) Não';
COMMENT ON COLUMN SEFAZ_SEG.TA_PAPEL_SISTEMA.USUARIO_EXCLUSAO IS 'Usuário que fez a exclusão do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_PAPEL_SISTEMA.DATA_EXCLUSAO IS 'Data - hora exclusão';


CREATE TABLE SEFAZ_SEG.TA_OPCAO_APLICACAO (
  IDENTIFICACAO_OPCAO_APLICACAO  number(10) CONSTRAINT NN_OPCAO_APLICACAO1 NOT NULL, 
  IDENTIFICACAO_APLICACAO_MODULO number(10) CONSTRAINT NN_OPCAO_APLICACAO2 NOT NULL, 
  CASO_USO                       varchar2(10) CONSTRAINT NN_OPCAO_APLICACAO3 NOT NULL, 
  DESCRIPCAO_OPCAO               varchar2(60) CONSTRAINT NN_OPCAO_APLICACAO4 NOT NULL, 
  OPCAO_URL                      varchar2(100) CONSTRAINT NN_OPCAO_APLICACAO5 NOT NULL, 
  AJUDA_OPCAO                    clob CONSTRAINT NN_OPCAO_APLICACAO6 NOT NULL,
  USUARIO_INSERCAO            	 varchar2(30) CONSTRAINT NN_OPCAO_APLICACAO7 NOT NULL, 
  DATA_INSERCAO               	 timestamp CONSTRAINT NN_OPCAO_APLICACAO8 NOT NULL, 
  USUARIO_ALTERACAO           	 varchar2(30), 
  DATA_ALTERACAO              	 timestamp, 
  REGISTRO_EXCLUIDO           	 char(1) DEFAULT 'N' CONSTRAINT NN_OPCAO_APLICACAO9 NOT NULL, 
  USUARIO_EXCLUSAO            	 varchar2(30), 
  DATA_EXCLUSAO               	 timestamp
);

ALTER TABLE SEFAZ_SEG.TA_OPCAO_APLICACAO ADD CONSTRAINT PK_OPCAO_APLICACAO PRIMARY KEY (IDENTIFICACAO_OPCAO_APLICACAO);
ALTER TABLE SEFAZ_SEG.TA_OPCAO_APLICACAO ADD CONSTRAINT CK_OPCAO_APLICACAO1 CHECK (REGISTRO_EXCLUIDO IN ('S','N'));
  
COMMENT ON TABLE SEFAZ_SEG.TA_OPCAO_APLICACAO IS 'Tabela para cadastrar as opções por aplicativo';
COMMENT ON COLUMN SEFAZ_SEG.TA_OPCAO_APLICACAO.IDENTIFICACAO_OPCAO_APLICACAO IS 'Identificação aplicativo por opção';
COMMENT ON COLUMN SEFAZ_SEG.TA_OPCAO_APLICACAO.IDENTIFICACAO_APLICACAO_MODULO IS 'Identificação do aplicaitvo';
COMMENT ON COLUMN SEFAZ_SEG.TA_OPCAO_APLICACAO.CASO_USO IS 'Caso de uso da opção para associar a ajuda';
COMMENT ON COLUMN SEFAZ_SEG.TA_OPCAO_APLICACAO.DESCRIPCAO_OPCAO IS 'Descrição da opção (funcionalidade) do sistema';
COMMENT ON COLUMN SEFAZ_SEG.TA_OPCAO_APLICACAO.OPCAO_URL IS 'Url da página jsp da opção';
COMMENT ON COLUMN SEFAZ_SEG.TA_OPCAO_APLICACAO.AJUDA_OPCAO IS 'Ajuda da opção associada no caso de uso, o formato é HTML';
COMMENT ON COLUMN SEFAZ_SEG.TA_OPCAO_APLICACAO.USUARIO_INSERCAO IS 'Usuário inserção do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_OPCAO_APLICACAO.DATA_INSERCAO IS 'Data - hora inserção';
COMMENT ON COLUMN SEFAZ_SEG.TA_OPCAO_APLICACAO.USUARIO_ALTERACAO IS 'Usuário alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_OPCAO_APLICACAO.DATA_ALTERACAO IS 'Data - hora alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_OPCAO_APLICACAO.REGISTRO_EXCLUIDO IS 'Indicador para registro excluido (S) Sim ou (N) Não';
COMMENT ON COLUMN SEFAZ_SEG.TA_OPCAO_APLICACAO.USUARIO_EXCLUSAO IS 'Usuário que fez a exclusão do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_OPCAO_APLICACAO.DATA_EXCLUSAO IS 'Data - hora exclusão';


CREATE TABLE SEFAZ_SEG.TA_APLICACAO_MODULO (
  IDENTIFICACAO_APLICACAO_MODULO number(10) CONSTRAINT NN_APLICACAO_MODULO1 NOT NULL, 
  IDENTIFICACAO_MODULO_SISTEMA   number(10) CONSTRAINT NN_APLICACAO_MODULO2 NOT NULL, 
  DESCRICAO_APLICACAO_MODULO     varchar2(30) CONSTRAINT NN_APLICACAO_MODULO3 NOT NULL,
  USUARIO_INSERCAO               varchar2(30) CONSTRAINT NN_APLICACAO_MODULO4 NOT NULL, 
  DATA_INSERCAO                  timestamp CONSTRAINT NN_APLICACAO_MODULO5 NOT NULL, 
  USUARIO_ALTERACAO              varchar2(30), 
  DATA_ALTERACAO                 timestamp, 
  REGISTRO_EXCLUIDO              char(1) DEFAULT 'N' CONSTRAINT NN_APLICACAO_MODULO6 NOT NULL, 
  USUARIO_EXCLUSAO               varchar2(30), 
  DATA_EXCLUSAO                  timestamp
);

  
ALTER TABLE SEFAZ_SEG.TA_APLICACAO_MODULO ADD CONSTRAINT PK_APLICACAO_MODULO PRIMARY KEY (IDENTIFICACAO_APLICACAO_MODULO);
ALTER TABLE SEFAZ_SEG.TA_APLICACAO_MODULO ADD CONSTRAINT CK_APLICACAO_MODULO1 CHECK (REGISTRO_EXCLUIDO IN ('S','N'));
  
COMMENT ON TABLE SEFAZ_SEG.TA_APLICACAO_MODULO IS 'Tabela para cadastrar as aplicações por módulo';
COMMENT ON COLUMN SEFAZ_SEG.TA_APLICACAO_MODULO.IDENTIFICACAO_APLICACAO_MODULO IS 'Identificação do aplicativo por módulo';
COMMENT ON COLUMN SEFAZ_SEG.TA_APLICACAO_MODULO.IDENTIFICACAO_MODULO_SISTEMA IS 'Identificação módulo por sistema';
COMMENT ON COLUMN SEFAZ_SEG.TA_APLICACAO_MODULO.DESCRICAO_APLICACAO_MODULO IS 'Descrição aplicação por módulo';
COMMENT ON COLUMN SEFAZ_SEG.TA_APLICACAO_MODULO.USUARIO_INSERCAO IS 'Usuário inserção do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_APLICACAO_MODULO.DATA_INSERCAO IS 'Data - hora inserção';
COMMENT ON COLUMN SEFAZ_SEG.TA_APLICACAO_MODULO.USUARIO_ALTERACAO IS 'Usuário alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_APLICACAO_MODULO.DATA_ALTERACAO IS 'Data - hora alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_APLICACAO_MODULO.REGISTRO_EXCLUIDO IS 'Indicador para registro excluido (S) Sim ou (N) Não';
COMMENT ON COLUMN SEFAZ_SEG.TA_APLICACAO_MODULO.USUARIO_EXCLUSAO IS 'Usuário que fez a exclusão do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_APLICACAO_MODULO.DATA_EXCLUSAO IS 'Data - hora exclusão';


CREATE TABLE SEFAZ_SEG.TA_MODULO_SISTEMA (
  IDENTIFICACAO_MODULO_SISTEMA number(10) CONSTRAINT NN_MODULO_SISTEMA1 NOT NULL, 
  ABREVIACAO_MODULO            char(3) CONSTRAINT NN_MODULO_SISTEMA2 NOT NULL, 
  DESCRICAO_MODULO_SISTEMA     varchar2(60) CONSTRAINT NN_MODULO_SISTEMA3 NOT NULL, 
  USUARIO_INSERCAO             varchar2(30) CONSTRAINT NN_MODULO_SISTEMA4 NOT NULL, 
  DATA_INSERCAO                timestamp CONSTRAINT NN_MODULO_SISTEMA5 NOT NULL, 
  USUARIO_ALTERACAO            varchar2(30), 
  DATA_ALTERACAO               timestamp, 
  REGISTRO_EXCLUIDO            char(1) DEFAULT 'N' CONSTRAINT NN_MODULO_SISTEMA6 NOT NULL, 
  USUARIO_EXCLUSAO             varchar2(30), 
  DATA_EXCLUSAO                timestamp
);
  
ALTER TABLE SEFAZ_SEG.TA_MODULO_SISTEMA ADD CONSTRAINT PK_MODULO_SISTEMA PRIMARY KEY (IDENTIFICACAO_MODULO_SISTEMA);
ALTER TABLE SEFAZ_SEG.TA_MODULO_SISTEMA ADD CONSTRAINT CK_MODULO_SISTEMA1 CHECK (REGISTRO_EXCLUIDO IN ('S','N'));

COMMENT ON TABLE SEFAZ_SEG.TA_MODULO_SISTEMA IS 'Tabela para cadastrar os módulos do sistema';
COMMENT ON COLUMN SEFAZ_SEG.TA_MODULO_SISTEMA.IDENTIFICACAO_MODULO_SISTEMA IS 'Identificação do módulo do sistema';
COMMENT ON COLUMN SEFAZ_SEG.TA_MODULO_SISTEMA.ABREVIACAO_MODULO IS 'Abreviação do modulo do sistema';
COMMENT ON COLUMN SEFAZ_SEG.TA_MODULO_SISTEMA.DESCRICAO_MODULO_SISTEMA IS 'Descrição do módulo do sistema';
COMMENT ON COLUMN SEFAZ_SEG.TA_MODULO_SISTEMA.USUARIO_INSERCAO IS 'Usuário inserção do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_MODULO_SISTEMA.DATA_INSERCAO IS 'Data - hora inserção';
COMMENT ON COLUMN SEFAZ_SEG.TA_MODULO_SISTEMA.USUARIO_ALTERACAO IS 'Usuário alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_MODULO_SISTEMA.DATA_ALTERACAO IS 'Data - hora alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_MODULO_SISTEMA.REGISTRO_EXCLUIDO IS 'Indicador para registro excluido (S) Sim ou (N) Não';
COMMENT ON COLUMN SEFAZ_SEG.TA_MODULO_SISTEMA.USUARIO_EXCLUSAO IS 'Usuário que fez a exclusão do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_MODULO_SISTEMA.DATA_EXCLUSAO IS 'Data - hora exclusão';


CREATE TABLE SEFAZ_SEG.TA_PERFIL_SISTEMA (
  IDENTIFICACAO_PERFIL number(10) CONSTRAINT NN_PERFIL_SISTEMA1 NOT NULL, 
  NOME_PERFIL          varchar2(30) CONSTRAINT NN_PERFIL_SISTEMA2 NOT NULL, 
  DESCRICAO_PERFIL     varchar2(120) CONSTRAINT NN_PERFIL_SISTEMA3 NOT NULL, 
  USUARIO_INSERCAO     varchar2(30) CONSTRAINT NN_PERFIL_SISTEMA4 NOT NULL, 
  DATA_INSERCAO        timestamp CONSTRAINT NN_PERFIL_SISTEMA5 NOT NULL, 
  USUARIO_ALTERACAO    varchar2(30), 
  DATA_ALTERACAO       timestamp, 
  REGISTRO_EXCLUIDO    char(1) DEFAULT 'N' CONSTRAINT NN_PERFIL_SISTEMA6 NOT NULL, 
  USUARIO_EXCLUSAO     varchar2(30), 
  DATA_EXCLUSAO        timestamp
);
  
ALTER TABLE SEFAZ_SEG.TA_PERFIL_SISTEMA ADD CONSTRAINT PK_PERFIL_SISTEMA PRIMARY KEY (IDENTIFICACAO_PERFIL);
ALTER TABLE SEFAZ_SEG.TA_PERFIL_SISTEMA ADD CONSTRAINT CK_PERFIL_SISTEMA1 CHECK (REGISTRO_EXCLUIDO IN ('S','N'));
  
COMMENT ON TABLE SEFAZ_SEG.TA_PERFIL_SISTEMA IS 'Tabela com os perfis do sistema para os usuários';
COMMENT ON COLUMN SEFAZ_SEG.TA_PERFIL_SISTEMA.IDENTIFICACAO_PERFIL IS 'Identificação do Perfil do Sistema';
COMMENT ON COLUMN SEFAZ_SEG.TA_PERFIL_SISTEMA.NOME_PERFIL IS 'Nome do Perfil do Sistema';
COMMENT ON COLUMN SEFAZ_SEG.TA_PERFIL_SISTEMA.DESCRICAO_PERFIL IS 'Descrição do Perfil do Sistema';
COMMENT ON COLUMN SEFAZ_SEG.TA_PERFIL_SISTEMA.USUARIO_INSERCAO IS 'Usuário inserção do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_PERFIL_SISTEMA.DATA_INSERCAO IS 'Data inserção do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_PERFIL_SISTEMA.USUARIO_ALTERACAO IS 'Usuário que fez a alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_PERFIL_SISTEMA.DATA_ALTERACAO IS 'Data alteração do regsitro';
COMMENT ON COLUMN SEFAZ_SEG.TA_PERFIL_SISTEMA.REGISTRO_EXCLUIDO IS 'Registro excluído do sistema. (S) Sim ou (N) Não';
COMMENT ON COLUMN SEFAZ_SEG.TA_PERFIL_SISTEMA.USUARIO_EXCLUSAO IS 'Usuário exclusão do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_PERFIL_SISTEMA.DATA_EXCLUSAO IS 'Data exclusão do registro';

CREATE TABLE SEFAZ_SEG.TA_USUARIO_PERFIL (
  IDENTIFICACAO_USUARIO_PERFIL number(10) CONSTRAINT NN_USUARIO_PERFIL1 NOT NULL, 
  CPF_USUARIO                  varchar2(11) CONSTRAINT NN_USUARIO_PERFIL2 NOT NULL, 
  IDENTIFICACAO_PERFIL         number(10) CONSTRAINT NN_USUARIO_PERFIL3 NOT NULL, 
  SITUACAO_PERFIL              char(1) CONSTRAINT NN_USUARIO_PERFIL4 NOT NULL, 
  USUARIO_INSERCAO             varchar2(30) CONSTRAINT NN_USUARIO_PERFIL5 NOT NULL, 
  DATA_INSERCAO                timestamp CONSTRAINT NN_USUARIO_PERFIL6 NOT NULL, 
  USUARIO_ALTERACAO            varchar2(30), 
  DATA_ALTERACAO               timestamp, 
  REGISTRO_EXCLUIDO            char(1) DEFAULT 'N' CONSTRAINT NN_USUARIO_PERFIL7 NOT NULL, 
  USUARIO_EXCLUSAO             varchar2(30), 
  DATA_EXCLUSAO                timestamp
);
  
ALTER TABLE SEFAZ_SEG.TA_USUARIO_PERFIL ADD CONSTRAINT PK_USUARIO_PERFIL PRIMARY KEY (IDENTIFICACAO_USUARIO_PERFIL);
ALTER TABLE SEFAZ_SEG.TA_USUARIO_PERFIL ADD CONSTRAINT CK_USUARIO_PERFIL1 CHECK (REGISTRO_EXCLUIDO IN ('S','N'));
ALTER TABLE SEFAZ_SEG.TA_USUARIO_PERFIL ADD CONSTRAINT CK_USUARIO_PERFIL2 CHECK (SITUACAO_PERFIL IN ('A','I'));
  
COMMENT ON TABLE SEFAZ_SEG.TA_USUARIO_PERFIL IS 'Tabela com a informação do perfis do usuário';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_PERFIL.IDENTIFICACAO_USUARIO_PERFIL IS 'Identificação sequêncial do usuário perfil';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_PERFIL.CPF_USUARIO IS 'CPF do usuário';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_PERFIL.IDENTIFICACAO_PERFIL IS 'Identiificação do Perfil do Usuário';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_PERFIL.SITUACAO_PERFIL IS 'Situação do perfil. (A) Ativo e (I) Inativo';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_PERFIL.USUARIO_INSERCAO IS 'Usuário que fez a inserção do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_PERFIL.DATA_INSERCAO IS 'Data inserção do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_PERFIL.USUARIO_ALTERACAO IS 'Usuário alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_PERFIL.DATA_ALTERACAO IS 'Data alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_PERFIL.REGISTRO_EXCLUIDO IS 'Reigstro excluído do sistema';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_PERFIL.USUARIO_EXCLUSAO IS 'Usuário exclusão do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_PERFIL.DATA_EXCLUSAO IS 'Data exclusão do registro';

CREATE TABLE SEFAZ_SEG.TA_TIPO_USUARIO (
  CODIGO_TIPO_USUARIO    number(2) CONSTRAINT NN_TIPO_USUARIO1 NOT NULL, 
  DESCRICAO_TIPO_USUARIO varchar2(30) CONSTRAINT NN_TIPO_USUARIO2 NOT NULL,
  USUARIO_INSERCAO       varchar2(30) CONSTRAINT NN_TIPO_USUARIO3 NOT NULL, 
  DATA_INSERCAO          timestamp CONSTRAINT NN_TIPO_USUARIO4 NOT NULL, 
  USUARIO_ALTERACAO      varchar2(30), 
  DATA_ALTERACAO         timestamp, 
  REGISTRO_EXCLUIDO      char(1) DEFAULT 'N' CONSTRAINT NN_TIPO_USUARIO5 NOT NULL, 
  USUARIO_EXCLUSAO       varchar2(30), 
  DATA_EXCLUSAO          timestamp
);

ALTER TABLE SEFAZ_SEG.TA_TIPO_USUARIO ADD CONSTRAINT PK_TIPO_USUARIO PRIMARY KEY (CODIGO_TIPO_USUARIO);
ALTER TABLE SEFAZ_SEG.TA_TIPO_USUARIO ADD CONSTRAINT CK_TIPO_USUARIO1 CHECK (REGISTRO_EXCLUIDO IN ('S','N'));
  
COMMENT ON TABLE SEFAZ_SEG.TA_TIPO_USUARIO IS 'Tabela com Tipo de usuário do sistema';
COMMENT ON COLUMN SEFAZ_SEG.TA_TIPO_USUARIO.CODIGO_TIPO_USUARIO IS 'Código do tipo de usuário';
COMMENT ON COLUMN SEFAZ_SEG.TA_TIPO_USUARIO.DESCRICAO_TIPO_USUARIO IS 'Descrição do tipo de usuário';
COMMENT ON COLUMN SEFAZ_SEG.TA_TIPO_USUARIO.USUARIO_INSERCAO IS 'Usuário que fez a inserção do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_TIPO_USUARIO.DATA_INSERCAO IS 'Data inserção do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_TIPO_USUARIO.USUARIO_ALTERACAO IS 'Usuário alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_TIPO_USUARIO.DATA_ALTERACAO IS 'Data alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_TIPO_USUARIO.REGISTRO_EXCLUIDO IS 'Reigstro excluído do sistema';
COMMENT ON COLUMN SEFAZ_SEG.TA_TIPO_USUARIO.USUARIO_EXCLUSAO IS 'Usuário exclusão do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_TIPO_USUARIO.DATA_EXCLUSAO IS 'Data exclusão do registro';


CREATE TABLE SEFAZ_SEG.TA_USUARIO_SISTEMA (
  CPF_USUARIO                  varchar2(11) CONSTRAINT NN_USUARIO_SISTEMA1 NOT NULL, 
  NOME_COMPLETO_USUARIO        varchar2(120) CONSTRAINT NN_USUARIO_SISTEMA2 NOT NULL, 
  CEP                          varchar2(8) CONSTRAINT NN_USUARIO_SISTEMA3 NOT NULL, 
  CODIGO_LOGRADOURO            char(3) CONSTRAINT NN_USUARIO_SISTEMA4 NOT NULL, 
  ENDERECO                     varchar2(100) CONSTRAINT NN_USUARIO_SISTEMA5 NOT NULL, 
  NUMERO_ENDERECO              number(8) CONSTRAINT NN_USUARIO_SISTEMA6 NOT NULL, 
  APARTAMENTO                  number(8), 
  COMPLEMENTO                  varchar2(30), 
  BAIRRO                       varchar2(100) CONSTRAINT NN_USUARIO_SISTEMA7 NOT NULL, 
  CODIGO_ESTADO                char(2) CONSTRAINT NN_USUARIO_SISTEMA8 NOT NULL, 
  CODIGO_MUNICIPIO             number(7) CONSTRAINT NN_USUARIO_SISTEMA9 NOT NULL, 
  TELEFONE_RESIDENCIAL         varchar2(20), 
  OUTRO_ENDERECO_CONTATO       varchar2(300), 
  CORREIO_ELETRONICO           varchar2(50) CONSTRAINT NN_USUARIO_SISTEMA10 NOT NULL, 
  TELEFONE_CELULAR             varchar2(10), 
  CODIGO_TIPO_USUARIO          number(2) CONSTRAINT NN_USUARIO_SISTEMA11 NOT NULL, 
  CRC                          varchar2(9), 
  SITUACAO_USUARIO             char(1) DEFAULT 'A' CONSTRAINT NN_USUARIO_SISTEMA12 NOT NULL, 
  ALTERAR_SENHA_PROXIMO_ACESSO char(1) DEFAULT 'S' CONSTRAINT NN_USUARIO_SISTEMA13 NOT NULL, 
  DATA_ULTIMA_ALTERACAO_SENHA  timestamp, 
  JUSTIFICACAO_CRIACAO         varchar2(300), 
  ESTA_BLOQUEADO               char(1) DEFAULT 'N' CONSTRAINT NN_USUARIO_SISTEMA14 NOT NULL, 
  DATA_DESBLOQUEIO             date, 
  USUARIO_INSERCAO             varchar2(30) CONSTRAINT NN_USUARIO_SISTEMA15 NOT NULL, 
  DATA_INSERCAO                timestamp  CONSTRAINT NN_USUARIO_SISTEMA16 NOT NULL, 
  USUARIO_ALTERACAO            varchar2(30), 
  DATA_ALTERACAO               timestamp, 
  REGISTRO_EXCLUIDO            char(1) DEFAULT 'N' CONSTRAINT NN_USUARIO_SISTEMA17 NOT NULL, 
  USUARIO_EXCLUSAO             varchar2(30), 
  DATA_EXCLUSAO                timestamp
);

ALTER TABLE SEFAZ_SEG.TA_USUARIO_SISTEMA ADD CONSTRAINT PK_USUARIO_SISTEMA PRIMARY KEY (CPF_USUARIO);
ALTER TABLE SEFAZ_SEG.TA_USUARIO_SISTEMA ADD CONSTRAINT CK_USUARIO_SISTEMA1 CHECK (SITUACAO_USUARIO IN ('A','I'));
ALTER TABLE SEFAZ_SEG.TA_USUARIO_SISTEMA ADD CONSTRAINT CK_USUARIO_SISTEMA2 CHECK (ALTERAR_SENHA_PROXIMO_ACESSO IN ('S','N'));
ALTER TABLE SEFAZ_SEG.TA_USUARIO_SISTEMA ADD CONSTRAINT CK_USUARIO_SISTEMA3 CHECK (ESTA_BLOQUEADO IN ('S','N'));
ALTER TABLE SEFAZ_SEG.TA_USUARIO_SISTEMA ADD CONSTRAINT CK_USUARIO_SISTEMA4 CHECK (REGISTRO_EXCLUIDO IN ('S','N'));

  
COMMENT ON TABLE SEFAZ_SEG.TA_USUARIO_SISTEMA IS 'Tabela com a Informação do usuário do sistema';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_SISTEMA.CPF_USUARIO IS 'CPF de usuário do sistema';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_SISTEMA.NOME_COMPLETO_USUARIO IS 'Nome completo do usuário do sistema';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_SISTEMA.CEP IS 'CEP do endereço do usuário';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_SISTEMA.CODIGO_LOGRADOURO IS 'Código Logradouro do endereço do usuário';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_SISTEMA.ENDERECO IS 'Endereço do usuário';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_SISTEMA.NUMERO_ENDERECO IS 'Número de endereço do usuário';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_SISTEMA.APARTAMENTO IS 'Apartamento do usuário se tiver';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_SISTEMA.COMPLEMENTO IS 'Complemento do endereço';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_SISTEMA.BAIRRO IS 'Bairro do endereço';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_SISTEMA.CODIGO_ESTADO IS 'Código do Estado Geográfico do Brasil';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_SISTEMA.CODIGO_MUNICIPIO IS 'Código IBGE do Municipio';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_SISTEMA.TELEFONE_RESIDENCIAL IS 'Telefone Residencial do usuário';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_SISTEMA.OUTRO_ENDERECO_CONTATO IS 'Outro Endereço para contato com o usuário';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_SISTEMA.CORREIO_ELETRONICO IS 'Correio eletrônico do usuário';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_SISTEMA.TELEFONE_CELULAR IS 'Telefone celular para contato com usuário';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_SISTEMA.CODIGO_TIPO_USUARIO IS 'Código de tipo de usuário';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_SISTEMA.CRC IS 'CRC do usuário para os contabilistas';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_SISTEMA.SITUACAO_USUARIO IS 'Situação do usuário, (A) Activo o (I) Inativo';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_SISTEMA.ALTERAR_SENHA_PROXIMO_ACESSO IS 'Campo para identificar se o usuário precisa mudar senha no próximo acesso. (S) Sim ou (N) Não';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_SISTEMA.DATA_ULTIMA_ALTERACAO_SENHA IS 'Data da última alteração de senha no sistema';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_SISTEMA.JUSTIFICACAO_CRIACAO IS 'Uma justificação da criação do usuário';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_SISTEMA.ESTA_BLOQUEADO IS 'Está usuario bloqueqado pelas 5 tentativas sem sucesso. Sim ou Não';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_SISTEMA.DATA_DESBLOQUEIO IS 'Data que o usuário será desbloqueado';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_SISTEMA.USUARIO_INSERCAO IS 'Usuário que fez a inserção do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_SISTEMA.DATA_INSERCAO IS 'Data de criação do usuário';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_SISTEMA.USUARIO_ALTERACAO IS 'Usuário que fez alguma alteração no registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_SISTEMA.DATA_ALTERACAO IS 'Data alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_SISTEMA.REGISTRO_EXCLUIDO IS 'Registro excluido. (S) Sim ou (N) Não';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_SISTEMA.USUARIO_EXCLUSAO IS ':Usuário que fez a exclusão do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_USUARIO_SISTEMA.DATA_EXCLUSAO IS 'Data de exclusão do registro';


CREATE TABLE SEFAZ_SEG.TA_LOG_NAVEGACAO (
  IDENTIFICACAO_NAVEGACAO number(10) CONSTRAINT NN_LOG_NAVEGACAO1 NOT NULL, 
  CPF_USUARIO             varchar2(11) CONSTRAINT NN_LOG_NAVEGACAO2 NOT NULL, 
  DATA_OPERACAO           timestamp CONSTRAINT NN_LOG_NAVEGACAO3 NOT NULL, 
  TIPO_OPERACAO           char(1) DEFAULT 'N' CONSTRAINT NN_LOG_NAVEGACAO4 NOT NULL, 
  DETALHE_NAVEGACAO       clob CONSTRAINT NN_LOG_NAVEGACAO5 NOT NULL,
  USUARIO_INSERCAO        varchar2(30) CONSTRAINT NN_LOG_NAVEGACAO6 NOT NULL, 
  DATA_INSERCAO           timestamp CONSTRAINT NN_LOG_NAVEGACAO7 NOT NULL, 
  USUARIO_ALTERACAO       varchar2(30), 
  DATA_ALTERACAO          timestamp, 
  REGISTRO_EXCLUIDO       char(1) DEFAULT 'N' CONSTRAINT NN_LOG_NAVEGACAO8 NOT NULL, 
  USUARIO_EXCLUSAO        varchar2(30), 
  DATA_EXCLUSAO           timestamp
);

ALTER TABLE SEFAZ_SEG.TA_LOG_NAVEGACAO ADD CONSTRAINT PK_LOG_NAVEGACAO PRIMARY KEY (IDENTIFICACAO_NAVEGACAO);
ALTER TABLE SEFAZ_SEG.TA_LOG_NAVEGACAO ADD CONSTRAINT CK_LOG_NAVEGACAO1 CHECK (TIPO_OPERACAO IN ('T','N'));
ALTER TABLE SEFAZ_SEG.TA_LOG_NAVEGACAO ADD CONSTRAINT CK_LOG_NAVEGACAO2 CHECK (REGISTRO_EXCLUIDO IN ('S','N'));
  
COMMENT ON TABLE SEFAZ_SEG.TA_LOG_NAVEGACAO IS 'Tabela que cadastra a informação da navegação do usuário no sistema';
COMMENT ON COLUMN SEFAZ_SEG.TA_LOG_NAVEGACAO.IDENTIFICACAO_NAVEGACAO IS 'Identificação do navegação, é um número sequêncial para salvar a informação na tabela';
COMMENT ON COLUMN SEFAZ_SEG.TA_LOG_NAVEGACAO.CPF_USUARIO IS 'CPF do usuário que fez a navegação';
COMMENT ON COLUMN SEFAZ_SEG.TA_LOG_NAVEGACAO.DATA_OPERACAO IS 'Data de Navegação';
COMMENT ON COLUMN SEFAZ_SEG.TA_LOG_NAVEGACAO.TIPO_OPERACAO IS 'Tipo Operação pode ser (N) de Navegação e (T) de Tentativa Negada';
COMMENT ON COLUMN SEFAZ_SEG.TA_LOG_NAVEGACAO.DETALHE_NAVEGACAO IS 'Arquivo em formato JSON con o detalhe da infromação do navegação';
COMMENT ON COLUMN SEFAZ_SEG.TA_LOG_NAVEGACAO.USUARIO_INSERCAO IS 'Usuário que fez a inserção do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_LOG_NAVEGACAO.DATA_INSERCAO IS 'Data de criação do usuário';
COMMENT ON COLUMN SEFAZ_SEG.TA_LOG_NAVEGACAO.USUARIO_ALTERACAO IS 'Usuário que fez alguma alteração no registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_LOG_NAVEGACAO.DATA_ALTERACAO IS 'Data alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_LOG_NAVEGACAO.REGISTRO_EXCLUIDO IS 'Registro excluido. (S) Sim ou (N) Não';
COMMENT ON COLUMN SEFAZ_SEG.TA_LOG_NAVEGACAO.USUARIO_EXCLUSAO IS ':Usuário que fez a exclusão do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_LOG_NAVEGACAO.DATA_EXCLUSAO IS 'Data de exclusão do registro';


CREATE TABLE SEFAZ_SEG.TA_CORREIO_CONTRIBUINTE (
  IDENTIFICACAO_CORREIO_ENVIADO number(10) CONSTRAINT NN_CORREIO_CONTRIBUINTE1 NOT NULL, 
  CPF_DESTINATARIO              varchar2(11) CONSTRAINT NN_CORREIO_CONTRIBUINTE2 NOT NULL, 
  CORREIO_ELETRONICO            varchar2(50) CONSTRAINT NN_CORREIO_CONTRIBUINTE3 NOT NULL, 
  DATA_ENVIO                    timestamp CONSTRAINT NN_CORREIO_CONTRIBUINTE4 NOT NULL, 
  ASSUNTO                       varchar2(100) CONSTRAINT NN_CORREIO_CONTRIBUINTE5 NOT NULL, 
  CONTEUDO                      clob CONSTRAINT NN_CORREIO_CONTRIBUINTE6 NOT NULL, 
  ANEXO                         blob, 
  USUARIO_INSERCAO              varchar2(30) CONSTRAINT NN_CORREIO_CONTRIBUINTE7 NOT NULL, 
  DATA_INSERCAO                 timestamp CONSTRAINT NN_CORREIO_CONTRIBUINTE8 NOT NULL, 
  USUARIO_ALTERACAO             varchar2(30), 
  DATA_ALTERACAO                timestamp, 
  REGISTRO_EXCLUIDO             char(1) DEFAULT 'N' CONSTRAINT NN_CORREIO_CONTRIBUINTE9 NOT NULL, 
  USUARIO_EXCLUSAO              varchar2(30), 
  DATA_EXCLUSAO                 timestamp
);
  
ALTER TABLE SEFAZ_SEG.TA_CORREIO_CONTRIBUINTE ADD CONSTRAINT PK_CORREIO_CONTRIBUINTE PRIMARY KEY (IDENTIFICACAO_CORREIO_ENVIADO);
ALTER TABLE SEFAZ_SEG.TA_CORREIO_CONTRIBUINTE ADD CONSTRAINT CK_CORREIO_CONTRIBUINTE1 CHECK (REGISTRO_EXCLUIDO IN ('S','N'));

COMMENT ON TABLE SEFAZ_SEG.TA_CORREIO_CONTRIBUINTE IS 'Tabela para salvar os correios eletrônicos enviados para os contribuintes';
COMMENT ON COLUMN SEFAZ_SEG.TA_CORREIO_CONTRIBUINTE.IDENTIFICACAO_CORREIO_ENVIADO IS 'Identificador sequêncial do cadastro de correio nesta tabela';
COMMENT ON COLUMN SEFAZ_SEG.TA_CORREIO_CONTRIBUINTE.CPF_DESTINATARIO IS 'CPF do destinatário do correio';
COMMENT ON COLUMN SEFAZ_SEG.TA_CORREIO_CONTRIBUINTE.CORREIO_ELETRONICO IS 'E-mail do destinatário';
COMMENT ON COLUMN SEFAZ_SEG.TA_CORREIO_CONTRIBUINTE.DATA_ENVIO IS 'Data - hora do correio enviado';
COMMENT ON COLUMN SEFAZ_SEG.TA_CORREIO_CONTRIBUINTE.ASSUNTO IS 'Assunto do correio';
COMMENT ON COLUMN SEFAZ_SEG.TA_CORREIO_CONTRIBUINTE.CONTEUDO IS 'Conteúdo do correio (txt, html)';
COMMENT ON COLUMN SEFAZ_SEG.TA_CORREIO_CONTRIBUINTE.ANEXO IS 'Arquivos que foram como anexo no correio, estão no formato de compressão';
COMMENT ON COLUMN SEFAZ_SEG.TA_CORREIO_CONTRIBUINTE.USUARIO_INSERCAO IS 'Usuário que executou a inserção do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_CORREIO_CONTRIBUINTE.DATA_INSERCAO IS 'Data Inserção do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_CORREIO_CONTRIBUINTE.USUARIO_ALTERACAO IS 'Usuário alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_CORREIO_CONTRIBUINTE.DATA_ALTERACAO IS 'Data de alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_CORREIO_CONTRIBUINTE.REGISTRO_EXCLUIDO IS 'Registro Excluido. (S) Sim ou (N) Nao';
COMMENT ON COLUMN SEFAZ_SEG.TA_CORREIO_CONTRIBUINTE.USUARIO_EXCLUSAO IS 'Usuário Exclusão';
COMMENT ON COLUMN SEFAZ_SEG.TA_CORREIO_CONTRIBUINTE.DATA_EXCLUSAO IS 'Data exclusão registro';


CREATE TABLE SEFAZ_SEG.TA_ERRO_PROCESSO_AUDITORIA (
  IDENTIFICACAO_ERRO_LOG number(10) CONSTRAINT NN_ERRO_PROCESSO_AUDITORIA1 NOT NULL, 
  NOME_PROGRAMA          varchar2(30) CONSTRAINT NN_ERRO_PROCESSO_AUDITORIA2 NOT NULL, 
  CODIGO_ERRO_SQL        number(10) CONSTRAINT NN_ERRO_PROCESSO_AUDITORIA3 NOT NULL, 
  ERRO_MENSAGEM_SQL      varchar2(64) CONSTRAINT NN_ERRO_PROCESSO_AUDITORIA4 NOT NULL, 
  ERRO_MENSAGEM          varchar2(100) CONSTRAINT NN_ERRO_PROCESSO_AUDITORIA5 NOT NULL, 
  DATA_ERRO              timestamp CONSTRAINT NN_ERRO_PROCESSO_AUDITORIA6 NOT NULL,
  USUARIO_INSERCAO       varchar2(30) CONSTRAINT NN_ERRO_PROCESSO_AUDITORIA7 NOT NULL, 
  DATA_INSERCAO          timestamp CONSTRAINT NN_ERRO_PROCESSO_AUDITORIA8 NOT NULL, 
  USUARIO_ALTERACAO      varchar2(30), 
  DATA_ALTERACAO         timestamp, 
  REGISTRO_EXCLUIDO      char(1) DEFAULT 'N' CONSTRAINT NN_ERRO_PROCESSO_AUDITORIA9 NOT NULL, 
  USUARIO_EXCLUSAO       varchar2(30), 
  DATA_EXCLUSAO          timestamp
);
  
ALTER TABLE SEFAZ_SEG.TA_ERRO_PROCESSO_AUDITORIA ADD CONSTRAINT PK_ERRO_PROCESSO_AUDITORIA PRIMARY KEY (IDENTIFICACAO_ERRO_LOG);
ALTER TABLE SEFAZ_SEG.TA_ERRO_PROCESSO_AUDITORIA ADD CONSTRAINT CK_ERRO_PROCESSO_AUDITORIA1 CHECK (REGISTRO_EXCLUIDO IN ('S','N'));

  
COMMENT ON TABLE SEFAZ_SEG.TA_ERRO_PROCESSO_AUDITORIA IS 'Tabela para armazenar os erros no momento de capturar uma auditoria';
COMMENT ON COLUMN SEFAZ_SEG.TA_ERRO_PROCESSO_AUDITORIA.IDENTIFICACAO_ERRO_LOG IS 'Identificador sequencial de log';
COMMENT ON COLUMN SEFAZ_SEG.TA_ERRO_PROCESSO_AUDITORIA.NOME_PROGRAMA IS 'Nome do programa que lança o erro';
COMMENT ON COLUMN SEFAZ_SEG.TA_ERRO_PROCESSO_AUDITORIA.CODIGO_ERRO_SQL IS 'Código de erro SQLCODE';
COMMENT ON COLUMN SEFAZ_SEG.TA_ERRO_PROCESSO_AUDITORIA.ERRO_MENSAGEM_SQL IS 'Mensagem de erro SQLERRM';
COMMENT ON COLUMN SEFAZ_SEG.TA_ERRO_PROCESSO_AUDITORIA.ERRO_MENSAGEM IS 'Mensagem de erro';
COMMENT ON COLUMN SEFAZ_SEG.TA_ERRO_PROCESSO_AUDITORIA.DATA_ERRO IS 'Data e hora do erro';
COMMENT ON COLUMN SEFAZ_SEG.TA_ERRO_PROCESSO_AUDITORIA.USUARIO_INSERCAO IS 'Usuário que executou a inserção do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_ERRO_PROCESSO_AUDITORIA.DATA_INSERCAO IS 'Data Inserção do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_ERRO_PROCESSO_AUDITORIA.USUARIO_ALTERACAO IS 'Usuário alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_ERRO_PROCESSO_AUDITORIA.DATA_ALTERACAO IS 'Data de alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_ERRO_PROCESSO_AUDITORIA.REGISTRO_EXCLUIDO IS 'Registro Excluido. (S) Sim ou (N) Nao';
COMMENT ON COLUMN SEFAZ_SEG.TA_ERRO_PROCESSO_AUDITORIA.USUARIO_EXCLUSAO IS 'Usuário Exclusão';
COMMENT ON COLUMN SEFAZ_SEG.TA_ERRO_PROCESSO_AUDITORIA.DATA_EXCLUSAO IS 'Data exclusão registro';


CREATE TABLE SEFAZ_SEG.TA_OPERACAO_AUDITADA (
  IDENTIFICACAO_AUDITORIA     number(15) CONSTRAINT NN_OPERACAO_AUDITADA1 NOT NULL, 
  NOME_TABELA                 varchar2(30) CONSTRAINT NN_OPERACAO_AUDITADA2 NOT NULL, 
  NOME_COMPUTADOR             varchar2(20) CONSTRAINT NN_OPERACAO_AUDITADA3 NOT NULL, 
  USUARIO_SISTEMA_OPERACIONAL varchar2(30) CONSTRAINT NN_OPERACAO_AUDITADA4 NOT NULL, 
  USUARIO_BANCO_DADOS         varchar2(30) CONSTRAINT NN_OPERACAO_AUDITADA5 NOT NULL, 
  APLICACAO_USADA             varchar2(30) CONSTRAINT NN_OPERACAO_AUDITADA6 NOT NULL, 
  ENDERECO_IP                 varchar2(15) CONSTRAINT NN_OPERACAO_AUDITADA7 NOT NULL, 
  DATA_OPERACAO               timestamp DEFAULT current_timestamp CONSTRAINT NN_OPERACAO_AUDITADA8 NOT NULL, 
  COLUNAS_ALTERADAS           clob CONSTRAINT NN_OPERACAO_AUDITADA9 NOT NULL,
  USUARIO_INSERCAO            varchar2(30) CONSTRAINT NN_OPERACAO_AUDITADA10 NOT NULL, 
  DATA_INSERCAO               timestamp CONSTRAINT NN_OPERACAO_AUDITADA11 NOT NULL, 
  USUARIO_ALTERACAO           varchar2(30), 
  DATA_ALTERACAO              timestamp, 
  REGISTRO_EXCLUIDO           char(1) DEFAULT 'N' CONSTRAINT NN_OPERACAO_AUDITADA12 NOT NULL, 
  USUARIO_EXCLUSAO            varchar2(30), 
  DATA_EXCLUSAO               timestamp
);
  
ALTER TABLE SEFAZ_SEG.TA_OPERACAO_AUDITADA ADD CONSTRAINT PK_OPERACAO_AUDITADA PRIMARY KEY (IDENTIFICACAO_AUDITORIA);
ALTER TABLE SEFAZ_SEG.TA_OPERACAO_AUDITADA ADD CONSTRAINT CK_OPERACAO_AUDITADA1 CHECK (REGISTRO_EXCLUIDO IN ('S','N'));

  
COMMENT ON TABLE SEFAZ_SEG.TA_OPERACAO_AUDITADA IS 'Tabela para armazenar toda a informação das operações de auditoria de alteraçoes do sistema';
COMMENT ON COLUMN SEFAZ_SEG.TA_OPERACAO_AUDITADA.IDENTIFICACAO_AUDITORIA IS 'Sequência para identificaçao do registro de auditoria';
COMMENT ON COLUMN SEFAZ_SEG.TA_OPERACAO_AUDITADA.NOME_TABELA IS 'Nome de tabela que foi alterada';
COMMENT ON COLUMN SEFAZ_SEG.TA_OPERACAO_AUDITADA.NOME_COMPUTADOR IS 'Nome do computador onde foi feita a operação';
COMMENT ON COLUMN SEFAZ_SEG.TA_OPERACAO_AUDITADA.USUARIO_SISTEMA_OPERACIONAL IS 'Login do usuário do sistema operativo responsável pela alteração';
COMMENT ON COLUMN SEFAZ_SEG.TA_OPERACAO_AUDITADA.USUARIO_BANCO_DADOS IS 'Login do usuário do banco de dados responsável pela alteração';
COMMENT ON COLUMN SEFAZ_SEG.TA_OPERACAO_AUDITADA.APLICACAO_USADA IS 'Programa usado para fazer a alteração';
COMMENT ON COLUMN SEFAZ_SEG.TA_OPERACAO_AUDITADA.ENDERECO_IP IS 'Endereco ip o computador usado';
COMMENT ON COLUMN SEFAZ_SEG.TA_OPERACAO_AUDITADA.DATA_OPERACAO IS 'Data e hora da alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_OPERACAO_AUDITADA.COLUNAS_ALTERADAS IS 'Os valores que foram alterados';
COMMENT ON COLUMN SEFAZ_SEG.TA_OPERACAO_AUDITADA.USUARIO_INSERCAO IS 'Usuário que executou a inserção do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_OPERACAO_AUDITADA.DATA_INSERCAO IS 'Data Inserção do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_OPERACAO_AUDITADA.USUARIO_ALTERACAO IS 'Usuário alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_OPERACAO_AUDITADA.DATA_ALTERACAO IS 'Data de alteração do registro';
COMMENT ON COLUMN SEFAZ_SEG.TA_OPERACAO_AUDITADA.REGISTRO_EXCLUIDO IS 'Registro Excluido. (S) Sim ou (N) Nao';
COMMENT ON COLUMN SEFAZ_SEG.TA_OPERACAO_AUDITADA.USUARIO_EXCLUSAO IS 'Usuário Exclusão';
COMMENT ON COLUMN SEFAZ_SEG.TA_OPERACAO_AUDITADA.DATA_EXCLUSAO IS 'Data exclusão registro';


ALTER TABLE SEFAZ_SEG.TA_PERFIL_PAPEL ADD CONSTRAINT FK_PERFIL_PAPEL1 FOREIGN KEY (IDENTIFICACAO_PERFIL) REFERENCES SEFAZ_SEG.TA_PERFIL_SISTEMA (IDENTIFICACAO_PERFIL);
ALTER TABLE SEFAZ_SEG.TA_PERFIL_PAPEL ADD CONSTRAINT FK_PERFIL_PAPEL2 FOREIGN KEY (IDENTIFICACAO_PAPEL) REFERENCES SEFAZ_SEG.TA_PAPEL_SISTEMA (IDENTIFICACAO_PAPEL);
ALTER TABLE SEFAZ_SEG.TA_PAPEL_OPCAO ADD CONSTRAINT FK_PAPEL_OPCAO1 FOREIGN KEY (IDENTIFICACAO_OPCAO_APLICACAO) REFERENCES SEFAZ_SEG.TA_OPCAO_APLICACAO (IDENTIFICACAO_OPCAO_APLICACAO);
ALTER TABLE SEFAZ_SEG.TA_PAPEL_OPCAO ADD CONSTRAINT FK_PAPEL_OPCAO2 FOREIGN KEY (IDENTIFICACAO_PAPEL) REFERENCES SEFAZ_SEG.TA_PAPEL_SISTEMA (IDENTIFICACAO_PAPEL);
ALTER TABLE SEFAZ_SEG.TA_OPCAO_APLICACAO ADD CONSTRAINT FK_OPCAO_APLICACAO1 FOREIGN KEY (IDENTIFICACAO_APLICACAO_MODULO) REFERENCES SEFAZ_SEG.TA_APLICACAO_MODULO (IDENTIFICACAO_APLICACAO_MODULO);
ALTER TABLE SEFAZ_SEG.TA_APLICACAO_MODULO ADD CONSTRAINT FK_APLICACAO_MODULO1 FOREIGN KEY (IDENTIFICACAO_MODULO_SISTEMA) REFERENCES SEFAZ_SEG.TA_MODULO_SISTEMA (IDENTIFICACAO_MODULO_SISTEMA);
ALTER TABLE SEFAZ_SEG.TA_USUARIO_PERFIL ADD CONSTRAINT FK_USUARIO_PERFIL1 FOREIGN KEY (IDENTIFICACAO_PERFIL) REFERENCES SEFAZ_SEG.TA_PERFIL_SISTEMA (IDENTIFICACAO_PERFIL);
ALTER TABLE SEFAZ_SEG.TA_USUARIO_PERFIL ADD CONSTRAINT FK_USUARIO_PERFIL2 FOREIGN KEY (CPF_USUARIO) REFERENCES SEFAZ_SEG.TA_USUARIO_SISTEMA (CPF_USUARIO);
ALTER TABLE SEFAZ_SEG.TA_USUARIO_SISTEMA ADD CONSTRAINT FK_USUARIO_SISTEMA1 FOREIGN KEY (CODIGO_TIPO_USUARIO) REFERENCES SEFAZ_SEG.TA_TIPO_USUARIO (CODIGO_TIPO_USUARIO);
ALTER TABLE SEFAZ_SEG.TA_USUARIO_SISTEMA ADD CONSTRAINT FK_USUARIO_SISTEMA2 FOREIGN KEY (CODIGO_MUNICIPIO) REFERENCES SEFAZ_CAT.TA_MUNICIPIO (CODIGO_IBGE);
ALTER TABLE SEFAZ_SEG.TA_USUARIO_SISTEMA ADD CONSTRAINT FK_USUARIO_SISTEMA3 FOREIGN KEY (CODIGO_ESTADO) REFERENCES SEFAZ_CAT.TA_ESTADO (UNIDADE_FEDERACAO);
--ALTER TABLE SEFAZ_SEG.TA_USUARIO_SISTEMA ADD CONSTRAINT FK_USUARIO_SISTEMA4 FOREIGN KEY (CODIGO_LOGRADOURO) REFERENCES SEFAZ_CAT.TA_LOGRADOURO (CODIGO_LOGRADOURO);
ALTER TABLE SEFAZ_SEG.TA_HISTORICO_LOGIN_SISTEMA ADD CONSTRAINT FK_HISTORICO_LOGIN_SISTEMA1 FOREIGN KEY (CPF_USUARIO) REFERENCES SEFAZ_SEG.TA_USUARIO_SISTEMA (CPF_USUARIO);
ALTER TABLE SEFAZ_SEG.TA_CORREIO_CONTRIBUINTE ADD CONSTRAINT FK_CORREIO_CONTRIBUINTE FOREIGN KEY (CPF_DESTINATARIO) REFERENCES SEFAZ_SEG.TA_USUARIO_SISTEMA (CPF_USUARIO);
ALTER TABLE SEFAZ_SEG.TA_LOG_NAVEGACAO ADD CONSTRAINT FK_LOG_NAVEGACAO FOREIGN KEY (CPF_USUARIO) REFERENCES SEFAZ_SEG.TA_USUARIO_SISTEMA (CPF_USUARIO);
ALTER TABLE SEFAZ_SEG.TA_USUARIO_POSTO_TRABALHO ADD CONSTRAINT FK_USUARIO_POSTO_TRABALHO1 FOREIGN KEY (IDENTIFICACAO_POSTO_TRABALHO) REFERENCES SEFAZ_SEG.TA_POSTO_TRABALHO (IDENTIFICACAO_POSTO_TRABALHO);
ALTER TABLE SEFAZ_SEG.TA_USUARIO_POSTO_TRABALHO ADD CONSTRAINT FK_USUARIO_POSTO_TRABALHO2 FOREIGN KEY (CPF_USUARIO) REFERENCES SEFAZ_SEG.TA_USUARIO_SISTEMA (CPF_USUARIO);
ALTER TABLE SEFAZ_SEG.TA_PROCURACAO_OPCAO ADD CONSTRAINT FK_PROCURACAO_OPCAO1 FOREIGN KEY (IDENTIFICACAO_OPCAO_APLICACAO) REFERENCES SEFAZ_SEG.TA_OPCAO_APLICACAO (IDENTIFICACAO_OPCAO_APLICACAO);
ALTER TABLE SEFAZ_SEG.TA_PROCURACAO_OPCAO ADD CONSTRAINT FK_PROCURACAO_OPCAO2 FOREIGN KEY (IDENTIFICACAO_PROCUR_USUARIO) REFERENCES SEFAZ_SEG.TA_PROCURACAO_USUARIO (IDENTIFICACAO_PROCUR_USUARIO);
ALTER TABLE SEFAZ_SEG.TA_SOLICITACAO_USUARIO ADD CONSTRAINT FK_SOLICITACAO_USUARIO1 FOREIGN KEY (CPF) REFERENCES SEFAZ_SEG.TA_USUARIO_SISTEMA (CPF_USUARIO);
ALTER TABLE SEFAZ_SEG.TA_POSTO_TRABALHO ADD CONSTRAINT FK_POSTO_TRABALHO1 FOREIGN KEY (IDENTIFICACAO_UNID_ORGANIZAC) REFERENCES SEFAZ_SEG.TA_UNIDADE_ORGANIZACIONAL (IDENTIFICACAO_UNID_ORGANIZAC);
ALTER TABLE SEFAZ_SEG.TA_SMS_CONTRIBUINTE ADD CONSTRAINT FK_SMS_CONTRIBUINTE1 FOREIGN KEY (CPF_DESTINATARIO) REFERENCES SEFAZ_SEG.TA_USUARIO_SISTEMA (CPF_USUARIO);

