-- Script para deletar as tabelas no esquema SEFAZ_ARR 
-- Autor: Cristiano Luis Schwaab
-- Data: 03 de Maio de 2016

-- Esquema SEFAZ_SEG
ALTER SESSION SET CURRENT_SCHEMA = SEFAZ_SEG;

DROP SEQUENCE SEFAZ_SEG.SQ_USUARIO_PRINCIPAL_EMPRESA;
DROP SEQUENCE SEFAZ_SEG.SQ_PROCURACAO_USUARIO;
DROP SEQUENCE SEFAZ_SEG.SQ_PROCURACAO_OPCAO;
DROP SEQUENCE SEFAZ_SEG.SQ_SOLICITACAO_USUARIO;
DROP SEQUENCE SEFAZ_SEG.SQ_POSTO_TRABALHO;
DROP SEQUENCE SEFAZ_SEG.SQ_UNIDADE_ORGANIZACIONAL;
DROP SEQUENCE SEFAZ_SEG.SQ_SMS_CONTRIBUINTE;
DROP SEQUENCE SEFAZ_SEG.SQ_HISTORICO_LOGIN_SISTEMA;
DROP SEQUENCE SEFAZ_SEG.SQ_PAPEL_SISTEMA;
DROP SEQUENCE SEFAZ_SEG.SQ_OPCAO_APLICACAO;
DROP SEQUENCE SEFAZ_SEG.SQ_APLICACAO_MODULO;
DROP SEQUENCE SEFAZ_SEG.SQ_MODULO_SISTEMA;
DROP SEQUENCE SEFAZ_SEG.SQ_PERFIL_SISTEMA;
DROP SEQUENCE SEFAZ_SEG.SQ_USUARIO_PERFIL;
DROP SEQUENCE SEFAZ_SEG.SQ_TIPO_USUARIO;
DROP SEQUENCE SEFAZ_SEG.SQ_LOG_NAVEGACAO;
DROP SEQUENCE SEFAZ_SEG.SQ_CORREIO_CONTRIBUINTE;
DROP SEQUENCE SEFAZ_SEG.SQ_ERRO_PROCESSO_AUDITORIA;
DROP SEQUENCE SEFAZ_SEG.SQ_OPERACAO_AUDITADA;

DROP TABLE SEFAZ_SEG.TA_USUARIO_POSTO_TRABALHO CASCADE CONSTRAINTS;
DROP TABLE SEFAZ_SEG.TA_USUARIO_PRINCIPAL_EMPRESA CASCADE CONSTRAINTS;
DROP TABLE SEFAZ_SEG.TA_PROCURACAO_USUARIO CASCADE CONSTRAINTS;
DROP TABLE SEFAZ_SEG.TA_PROCURACAO_OPCAO CASCADE CONSTRAINTS;
DROP TABLE SEFAZ_SEG.TA_SOLICITACAO_USUARIO CASCADE CONSTRAINTS;
DROP TABLE SEFAZ_SEG.TA_POSTO_TRABALHO CASCADE CONSTRAINTS;
DROP TABLE SEFAZ_SEG.TA_UNIDADE_ORGANIZACIONAL CASCADE CONSTRAINTS;
DROP TABLE SEFAZ_SEG.TA_SMS_CONTRIBUINTE CASCADE CONSTRAINTS;
DROP TABLE SEFAZ_SEG.TA_HISTORICO_LOGIN_SISTEMA CASCADE CONSTRAINTS;
DROP TABLE SEFAZ_SEG.TA_PAPEL_OPCAO CASCADE CONSTRAINTS;
DROP TABLE SEFAZ_SEG.TA_PERFIL_PAPEL CASCADE CONSTRAINTS;
DROP TABLE SEFAZ_SEG.TA_PAPEL_SISTEMA CASCADE CONSTRAINTS;
DROP TABLE SEFAZ_SEG.TA_OPCAO_APLICACAO CASCADE CONSTRAINTS;
DROP TABLE SEFAZ_SEG.TA_APLICACAO_MODULO CASCADE CONSTRAINTS;
DROP TABLE SEFAZ_SEG.TA_MODULO_SISTEMA CASCADE CONSTRAINTS;
DROP TABLE SEFAZ_SEG.TA_PERFIL_SISTEMA CASCADE CONSTRAINTS;
DROP TABLE SEFAZ_SEG.TA_USUARIO_PERFIL CASCADE CONSTRAINTS;
DROP TABLE SEFAZ_CAT.TA_MUNICIPIO_ESTADO CASCADE CONSTRAINTS;
DROP TABLE SEFAZ_CAT.TA_ESTADO_PAIS CASCADE CONSTRAINTS;
DROP TABLE SEFAZ_CAT.TA_LOGRADOURO CASCADE CONSTRAINTS;
DROP TABLE SEFAZ_SEG.TA_TIPO_USUARIO CASCADE CONSTRAINTS;
DROP TABLE SEFAZ_SEG.TA_USUARIO_SISTEMA CASCADE CONSTRAINTS;
DROP TABLE SEFAZ_SEG.TA_LOG_NAVEGACAO CASCADE CONSTRAINTS;
DROP TABLE SEFAZ_SEG.TA_CORREIO_CONTRIBUINTE CASCADE CONSTRAINTS;
DROP TABLE SEFAZ_SEG.TA_ERRO_PROCESSO_AUDITORIA CASCADE CONSTRAINTS;
DROP TABLE SEFAZ_SEG.TA_OPERACAO_AUDITADA CASCADE CONSTRAINTS;
